//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:51:42 PM GMT 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JourneyStopTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JourneyStopTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="origin"/>
 *     &lt;enumeration value="intermediate"/>
 *     &lt;enumeration value="destination"/>
 *     &lt;enumeration value="originDestination"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JourneyStopTypeEnumeration")
@XmlEnum
public enum JourneyStopTypeEnumeration {

    @XmlEnumValue("origin")
    ORIGIN("origin"),
    @XmlEnumValue("intermediate")
    INTERMEDIATE("intermediate"),
    @XmlEnumValue("destination")
    DESTINATION("destination"),
    @XmlEnumValue("originDestination")
    ORIGIN_DESTINATION("originDestination");
    private final String value;

    JourneyStopTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JourneyStopTypeEnumeration fromValue(String v) {
        for (JourneyStopTypeEnumeration c: JourneyStopTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
