//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Common type for a journey pattern and a vehicle journey.
 * 
 * <p>Java class for AbstractServicePatternStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractServicePatternStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.transxchange.org.uk/}CommonJourneyGroup"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.transxchange.org.uk/}ModificationDetailsGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractServicePatternStructure", propOrder = {
    "privateCode",
    "destinationDisplay",
    "operatorRef",
    "direction",
    "operational",
    "operatingProfile",
    "timeDemand",
    "layoverPoint",
    "garageRef",
    "description"
})
@XmlSeeAlso({
    AbstractJourneyPatternStructure.class,
    AbstractVehicleJourneyStructure.class
})
public class AbstractServicePatternStructure {

    @XmlElement(name = "PrivateCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String privateCode;
    @XmlElement(name = "DestinationDisplay")
    protected NaturalLanguageStringStructure destinationDisplay;
    @XmlElement(name = "OperatorRef")
    protected OperatorRefStructure operatorRef;
    @XmlElement(name = "Direction", defaultValue = "inherit")
    protected JourneyPatternVehicleDirectionEnumeration direction;
    @XmlElement(name = "Operational")
    protected AbstractServicePatternStructure.Operational operational;
    @XmlElement(name = "OperatingProfile")
    protected OperatingProfileStructure operatingProfile;
    @XmlElement(name = "TimeDemand")
    protected TimeDemandEnumeration timeDemand;
    @XmlElement(name = "LayoverPoint")
    protected List<AbstractServicePatternStructure.LayoverPoint> layoverPoint;
    @XmlElement(name = "GarageRef")
    protected List<GarageRefStructure> garageRef;
    @XmlElement(name = "Description")
    protected NaturalLanguageStringStructure description;
    @XmlAttribute(name = "CreationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "ModificationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modificationDateTime;
    @XmlAttribute(name = "Modification")
    protected ModificationEnumeration modification;
    @XmlAttribute(name = "RevisionNumber")
    protected BigInteger revisionNumber;
    @XmlAttribute(name = "Status")
    protected StatusEnumeration status;

    /**
     * Gets the value of the privateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateCode() {
        return privateCode;
    }

    /**
     * Sets the value of the privateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateCode(String value) {
        this.privateCode = value;
    }

    /**
     * Gets the value of the destinationDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getDestinationDisplay() {
        return destinationDisplay;
    }

    /**
     * Sets the value of the destinationDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setDestinationDisplay(NaturalLanguageStringStructure value) {
        this.destinationDisplay = value;
    }

    /**
     * Gets the value of the operatorRef property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorRefStructure }
     *     
     */
    public OperatorRefStructure getOperatorRef() {
        return operatorRef;
    }

    /**
     * Sets the value of the operatorRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorRefStructure }
     *     
     */
    public void setOperatorRef(OperatorRefStructure value) {
        this.operatorRef = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyPatternVehicleDirectionEnumeration }
     *     
     */
    public JourneyPatternVehicleDirectionEnumeration getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyPatternVehicleDirectionEnumeration }
     *     
     */
    public void setDirection(JourneyPatternVehicleDirectionEnumeration value) {
        this.direction = value;
    }

    /**
     * Gets the value of the operational property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractServicePatternStructure.Operational }
     *     
     */
    public AbstractServicePatternStructure.Operational getOperational() {
        return operational;
    }

    /**
     * Sets the value of the operational property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractServicePatternStructure.Operational }
     *     
     */
    public void setOperational(AbstractServicePatternStructure.Operational value) {
        this.operational = value;
    }

    /**
     * Gets the value of the operatingProfile property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingProfileStructure }
     *     
     */
    public OperatingProfileStructure getOperatingProfile() {
        return operatingProfile;
    }

    /**
     * Sets the value of the operatingProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingProfileStructure }
     *     
     */
    public void setOperatingProfile(OperatingProfileStructure value) {
        this.operatingProfile = value;
    }

    /**
     * Gets the value of the timeDemand property.
     * 
     * @return
     *     possible object is
     *     {@link TimeDemandEnumeration }
     *     
     */
    public TimeDemandEnumeration getTimeDemand() {
        return timeDemand;
    }

    /**
     * Sets the value of the timeDemand property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeDemandEnumeration }
     *     
     */
    public void setTimeDemand(TimeDemandEnumeration value) {
        this.timeDemand = value;
    }

    /**
     * Gets the value of the layoverPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layoverPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayoverPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractServicePatternStructure.LayoverPoint }
     * 
     * 
     */
    public List<AbstractServicePatternStructure.LayoverPoint> getLayoverPoint() {
        if (layoverPoint == null) {
            layoverPoint = new ArrayList<AbstractServicePatternStructure.LayoverPoint>();
        }
        return this.layoverPoint;
    }

    /**
     * Gets the value of the garageRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the garageRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGarageRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GarageRefStructure }
     * 
     * 
     */
    public List<GarageRefStructure> getGarageRef() {
        if (garageRef == null) {
            garageRef = new ArrayList<GarageRefStructure>();
        }
        return this.garageRef;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setDescription(NaturalLanguageStringStructure value) {
        this.description = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the modificationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModificationDateTime() {
        return modificationDateTime;
    }

    /**
     * Sets the value of the modificationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModificationDateTime(XMLGregorianCalendar value) {
        this.modificationDateTime = value;
    }

    /**
     * Gets the value of the modification property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationEnumeration }
     *     
     */
    public ModificationEnumeration getModification() {
        if (modification == null) {
            return ModificationEnumeration.NEW;
        } else {
            return modification;
        }
    }

    /**
     * Sets the value of the modification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationEnumeration }
     *     
     */
    public void setModification(ModificationEnumeration value) {
        this.modification = value;
    }

    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevisionNumber(BigInteger value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusEnumeration }
     *     
     */
    public StatusEnumeration getStatus() {
        if (status == null) {
            return StatusEnumeration.ACTIVE;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusEnumeration }
     *     
     */
    public void setStatus(StatusEnumeration value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.transxchange.org.uk/}LayoverPointStructure">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LayoverPoint
        extends LayoverPointStructure
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Block" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Description" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure"/>
     *                   &lt;element name="BlockNumber" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
     *                   &lt;element name="Note" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="VehicleType" type="{http://www.transxchange.org.uk/}VehicleTypeStructure" minOccurs="0"/>
     *         &lt;element name="TicketMachine" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TicketMachineServiceCode" type="{http://www.transxchange.org.uk/}TicketMachineJourneyCodeType" minOccurs="0"/>
     *                   &lt;element name="JourneyCode" type="{http://www.transxchange.org.uk/}TicketMachineJourneyCodeType" minOccurs="0"/>
     *                   &lt;element name="Direction" type="{http://www.transxchange.org.uk/}VehicleDirectionEnumeration" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "block",
        "vehicleType",
        "ticketMachine"
    })
    public static class Operational {

        @XmlElement(name = "Block")
        protected AbstractServicePatternStructure.Operational.Block block;
        @XmlElement(name = "VehicleType")
        protected VehicleTypeStructure vehicleType;
        @XmlElement(name = "TicketMachine")
        protected AbstractServicePatternStructure.Operational.TicketMachine ticketMachine;

        /**
         * Gets the value of the block property.
         * 
         * @return
         *     possible object is
         *     {@link AbstractServicePatternStructure.Operational.Block }
         *     
         */
        public AbstractServicePatternStructure.Operational.Block getBlock() {
            return block;
        }

        /**
         * Sets the value of the block property.
         * 
         * @param value
         *     allowed object is
         *     {@link AbstractServicePatternStructure.Operational.Block }
         *     
         */
        public void setBlock(AbstractServicePatternStructure.Operational.Block value) {
            this.block = value;
        }

        /**
         * Gets the value of the vehicleType property.
         * 
         * @return
         *     possible object is
         *     {@link VehicleTypeStructure }
         *     
         */
        public VehicleTypeStructure getVehicleType() {
            return vehicleType;
        }

        /**
         * Sets the value of the vehicleType property.
         * 
         * @param value
         *     allowed object is
         *     {@link VehicleTypeStructure }
         *     
         */
        public void setVehicleType(VehicleTypeStructure value) {
            this.vehicleType = value;
        }

        /**
         * Gets the value of the ticketMachine property.
         * 
         * @return
         *     possible object is
         *     {@link AbstractServicePatternStructure.Operational.TicketMachine }
         *     
         */
        public AbstractServicePatternStructure.Operational.TicketMachine getTicketMachine() {
            return ticketMachine;
        }

        /**
         * Sets the value of the ticketMachine property.
         * 
         * @param value
         *     allowed object is
         *     {@link AbstractServicePatternStructure.Operational.TicketMachine }
         *     
         */
        public void setTicketMachine(AbstractServicePatternStructure.Operational.TicketMachine value) {
            this.ticketMachine = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Description" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure"/>
         *         &lt;element name="BlockNumber" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
         *         &lt;element name="Note" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "blockNumber",
            "note"
        })
        public static class Block {

            @XmlElement(name = "Description", required = true)
            protected NaturalLanguageStringStructure description;
            @XmlElement(name = "BlockNumber")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String blockNumber;
            @XmlElement(name = "Note")
            protected NaturalLanguageStringStructure note;

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link NaturalLanguageStringStructure }
             *     
             */
            public NaturalLanguageStringStructure getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link NaturalLanguageStringStructure }
             *     
             */
            public void setDescription(NaturalLanguageStringStructure value) {
                this.description = value;
            }

            /**
             * Gets the value of the blockNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBlockNumber() {
                return blockNumber;
            }

            /**
             * Sets the value of the blockNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBlockNumber(String value) {
                this.blockNumber = value;
            }

            /**
             * Gets the value of the note property.
             * 
             * @return
             *     possible object is
             *     {@link NaturalLanguageStringStructure }
             *     
             */
            public NaturalLanguageStringStructure getNote() {
                return note;
            }

            /**
             * Sets the value of the note property.
             * 
             * @param value
             *     allowed object is
             *     {@link NaturalLanguageStringStructure }
             *     
             */
            public void setNote(NaturalLanguageStringStructure value) {
                this.note = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TicketMachineServiceCode" type="{http://www.transxchange.org.uk/}TicketMachineJourneyCodeType" minOccurs="0"/>
         *         &lt;element name="JourneyCode" type="{http://www.transxchange.org.uk/}TicketMachineJourneyCodeType" minOccurs="0"/>
         *         &lt;element name="Direction" type="{http://www.transxchange.org.uk/}VehicleDirectionEnumeration" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ticketMachineServiceCode",
            "journeyCode",
            "direction"
        })
        public static class TicketMachine {

            @XmlElement(name = "TicketMachineServiceCode")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String ticketMachineServiceCode;
            @XmlElement(name = "JourneyCode")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String journeyCode;
            @XmlElement(name = "Direction")
            protected VehicleDirectionEnumeration direction;

            /**
             * Gets the value of the ticketMachineServiceCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTicketMachineServiceCode() {
                return ticketMachineServiceCode;
            }

            /**
             * Sets the value of the ticketMachineServiceCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTicketMachineServiceCode(String value) {
                this.ticketMachineServiceCode = value;
            }

            /**
             * Gets the value of the journeyCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJourneyCode() {
                return journeyCode;
            }

            /**
             * Sets the value of the journeyCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJourneyCode(String value) {
                this.journeyCode = value;
            }

            /**
             * Gets the value of the direction property.
             * 
             * @return
             *     possible object is
             *     {@link VehicleDirectionEnumeration }
             *     
             */
            public VehicleDirectionEnumeration getDirection() {
                return direction;
            }

            /**
             * Sets the value of the direction property.
             * 
             * @param value
             *     allowed object is
             *     {@link VehicleDirectionEnumeration }
             *     
             */
            public void setDirection(VehicleDirectionEnumeration value) {
                this.direction = value;
            }

        }

    }

}
