//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data type for an annotated reference to a locality that is defined elsewhere using a StopPointStructure. The annotation is the stop's common name.
 * 
 * <p>Java class for AnnotatedNptgLocalityRefStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotatedNptgLocalityRefStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NptgLocalityRef" type="{http://www.transxchange.org.uk/}NptgLocalityRefStructure"/>
 *         &lt;element name="LocalityName" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *         &lt;element name="LocalityQualifier" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotatedNptgLocalityRefStructure", propOrder = {
    "nptgLocalityRef",
    "localityName",
    "localityQualifier"
})
public class AnnotatedNptgLocalityRefStructure {

    @XmlElement(name = "NptgLocalityRef", required = true)
    protected NptgLocalityRefStructure nptgLocalityRef;
    @XmlElement(name = "LocalityName")
    protected NaturalLanguageStringStructure localityName;
    @XmlElement(name = "LocalityQualifier")
    protected NaturalLanguageStringStructure localityQualifier;

    /**
     * Gets the value of the nptgLocalityRef property.
     * 
     * @return
     *     possible object is
     *     {@link NptgLocalityRefStructure }
     *     
     */
    public NptgLocalityRefStructure getNptgLocalityRef() {
        return nptgLocalityRef;
    }

    /**
     * Sets the value of the nptgLocalityRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link NptgLocalityRefStructure }
     *     
     */
    public void setNptgLocalityRef(NptgLocalityRefStructure value) {
        this.nptgLocalityRef = value;
    }

    /**
     * Gets the value of the localityName property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getLocalityName() {
        return localityName;
    }

    /**
     * Sets the value of the localityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setLocalityName(NaturalLanguageStringStructure value) {
        this.localityName = value;
    }

    /**
     * Gets the value of the localityQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getLocalityQualifier() {
        return localityQualifier;
    }

    /**
     * Sets the value of the localityQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setLocalityQualifier(NaturalLanguageStringStructure value) {
        this.localityQualifier = value;
    }

}
