//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthorityNameEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthorityNameEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Aberdeen"/>
 *     &lt;enumeration value="Aberdeenshire"/>
 *     &lt;enumeration value="Angus"/>
 *     &lt;enumeration value="ArgyllAndBute"/>
 *     &lt;enumeration value="BathAndNorthEastSomerset"/>
 *     &lt;enumeration value="Bedfordshire"/>
 *     &lt;enumeration value="Bedford"/>
 *     &lt;enumeration value="CentralBedfordshire"/>
 *     &lt;enumeration value="Berkshire"/>
 *     &lt;enumeration value="BlackburnWithDarwen"/>
 *     &lt;enumeration value="Blackpool"/>
 *     &lt;enumeration value="BlaenauGwent"/>
 *     &lt;enumeration value="Bournemouth"/>
 *     &lt;enumeration value="BracknellForest"/>
 *     &lt;enumeration value="Bridgend"/>
 *     &lt;enumeration value="BrightonAndHove"/>
 *     &lt;enumeration value="Bristol"/>
 *     &lt;enumeration value="Buckinghamshire"/>
 *     &lt;enumeration value="Caerphilly"/>
 *     &lt;enumeration value="Cambridgeshire"/>
 *     &lt;enumeration value="Cardiff"/>
 *     &lt;enumeration value="Carmarthenshire"/>
 *     &lt;enumeration value="CentroWestMidlands"/>
 *     &lt;enumeration value="Ceredigion"/>
 *     &lt;enumeration value="ChannelIslands"/>
 *     &lt;enumeration value="Cheshire"/>
 *     &lt;enumeration value="CheshireEast"/>
 *     &lt;enumeration value="CheshireWestAndChester"/>
 *     &lt;enumeration value="CheshireWestAndCheshire"/>
 *     &lt;enumeration value="Clackmannanshire"/>
 *     &lt;enumeration value="ComhairleNanEileanSiar"/>
 *     &lt;enumeration value="Conwy"/>
 *     &lt;enumeration value="CornwallAndScillies"/>
 *     &lt;enumeration value="Cumbria"/>
 *     &lt;enumeration value="Darlington"/>
 *     &lt;enumeration value="Denbighshire"/>
 *     &lt;enumeration value="Derby"/>
 *     &lt;enumeration value="Derbyshire"/>
 *     &lt;enumeration value="Devon"/>
 *     &lt;enumeration value="Dorset"/>
 *     &lt;enumeration value="DumfriesAndGalloway"/>
 *     &lt;enumeration value="Dundee"/>
 *     &lt;enumeration value="Durham"/>
 *     &lt;enumeration value="EastAyrshire"/>
 *     &lt;enumeration value="EastDunbartonshire"/>
 *     &lt;enumeration value="EastLothian"/>
 *     &lt;enumeration value="EastRenfrewshire"/>
 *     &lt;enumeration value="EastRidingOfYorkshire"/>
 *     &lt;enumeration value="EastSussex"/>
 *     &lt;enumeration value="Edinburgh"/>
 *     &lt;enumeration value="Essex"/>
 *     &lt;enumeration value="Falkirk"/>
 *     &lt;enumeration value="Fife"/>
 *     &lt;enumeration value="Flintshire"/>
 *     &lt;enumeration value="Glasgow"/>
 *     &lt;enumeration value="Gloucestershire"/>
 *     &lt;enumeration value="GMPTE"/>
 *     &lt;enumeration value="Gwynedd"/>
 *     &lt;enumeration value="Halton"/>
 *     &lt;enumeration value="Hampshire"/>
 *     &lt;enumeration value="Hartlepool"/>
 *     &lt;enumeration value="Havering"/>
 *     &lt;enumeration value="Herefordshire"/>
 *     &lt;enumeration value="Hertfordshire"/>
 *     &lt;enumeration value="Highland"/>
 *     &lt;enumeration value="Inverclyde"/>
 *     &lt;enumeration value="IsleOfAnglesey"/>
 *     &lt;enumeration value="IsleOfMan"/>
 *     &lt;enumeration value="IsleOfWight"/>
 *     &lt;enumeration value="Kent"/>
 *     &lt;enumeration value="KingstonUponHull"/>
 *     &lt;enumeration value="Lancashire"/>
 *     &lt;enumeration value="Leicester"/>
 *     &lt;enumeration value="Leicestershire"/>
 *     &lt;enumeration value="Lincolnshire"/>
 *     &lt;enumeration value="London"/>
 *     &lt;enumeration value="Luton"/>
 *     &lt;enumeration value="Medway"/>
 *     &lt;enumeration value="Merseytravel"/>
 *     &lt;enumeration value="MerthyrTydfil"/>
 *     &lt;enumeration value="Metro"/>
 *     &lt;enumeration value="Middlesbrough"/>
 *     &lt;enumeration value="Midlothian"/>
 *     &lt;enumeration value="MiltonKeynes"/>
 *     &lt;enumeration value="Monmouthshire"/>
 *     &lt;enumeration value="Moray"/>
 *     &lt;enumeration value="NeathPortTalbot"/>
 *     &lt;enumeration value="Newport"/>
 *     &lt;enumeration value="NexusTynesde"/>
 *     &lt;enumeration value="Norfolk"/>
 *     &lt;enumeration value="NorthAyrshire"/>
 *     &lt;enumeration value="NorthEastLincolnshire"/>
 *     &lt;enumeration value="NorthLanarkshire"/>
 *     &lt;enumeration value="NorthLincolnshire"/>
 *     &lt;enumeration value="NorthernIreland"/>
 *     &lt;enumeration value="NorthSomerset"/>
 *     &lt;enumeration value="NorthYorkshire"/>
 *     &lt;enumeration value="Northamptonshire"/>
 *     &lt;enumeration value="Northumberland"/>
 *     &lt;enumeration value="Nottingham"/>
 *     &lt;enumeration value="Nottinghamshire"/>
 *     &lt;enumeration value="OrkneyIslands"/>
 *     &lt;enumeration value="Oxfordshire"/>
 *     &lt;enumeration value="Pembrokeshire"/>
 *     &lt;enumeration value="PerthAndKinross"/>
 *     &lt;enumeration value="Peterborough"/>
 *     &lt;enumeration value="Plymouth"/>
 *     &lt;enumeration value="Poole"/>
 *     &lt;enumeration value="Portsmouth"/>
 *     &lt;enumeration value="Powys"/>
 *     &lt;enumeration value="Reading"/>
 *     &lt;enumeration value="RedcarAndCleveland"/>
 *     &lt;enumeration value="Renfrewshire"/>
 *     &lt;enumeration value="RhonddaCynonTaff"/>
 *     &lt;enumeration value="Rutland"/>
 *     &lt;enumeration value="ScottishBorders"/>
 *     &lt;enumeration value="ShetlandIslands"/>
 *     &lt;enumeration value="Shropshire"/>
 *     &lt;enumeration value="Slough"/>
 *     &lt;enumeration value="Somerset"/>
 *     &lt;enumeration value="SouthAyrshire"/>
 *     &lt;enumeration value="SouthGloucestershire"/>
 *     &lt;enumeration value="SouthLanarkshire"/>
 *     &lt;enumeration value="SouthYorkshirePTE"/>
 *     &lt;enumeration value="Southampton"/>
 *     &lt;enumeration value="SouthendOnSea"/>
 *     &lt;enumeration value="Staffordshire"/>
 *     &lt;enumeration value="Stirling"/>
 *     &lt;enumeration value="StocktonOnTees"/>
 *     &lt;enumeration value="StokeOnTrent"/>
 *     &lt;enumeration value="StrathclydePTE"/>
 *     &lt;enumeration value="Suffolk"/>
 *     &lt;enumeration value="Surrey"/>
 *     &lt;enumeration value="Swansea"/>
 *     &lt;enumeration value="Swindon"/>
 *     &lt;enumeration value="TelfordAndWrekin"/>
 *     &lt;enumeration value="Thurrock"/>
 *     &lt;enumeration value="Torbay"/>
 *     &lt;enumeration value="Torfaen"/>
 *     &lt;enumeration value="Translink"/>
 *     &lt;enumeration value="ValeOfGlamorgan"/>
 *     &lt;enumeration value="Warrington"/>
 *     &lt;enumeration value="Warwickshire"/>
 *     &lt;enumeration value="WestBerkshire"/>
 *     &lt;enumeration value="WestDunbartonshire"/>
 *     &lt;enumeration value="WestLothian"/>
 *     &lt;enumeration value="WestSussex"/>
 *     &lt;enumeration value="Wiltshire"/>
 *     &lt;enumeration value="WindsorAndMaidenhead"/>
 *     &lt;enumeration value="Wokingham"/>
 *     &lt;enumeration value="Worcestershire"/>
 *     &lt;enumeration value="Wrexham"/>
 *     &lt;enumeration value="York"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuthorityNameEnumeration")
@XmlEnum
public enum AuthorityNameEnumeration {

    @XmlEnumValue("Aberdeen")
    ABERDEEN("Aberdeen"),
    @XmlEnumValue("Aberdeenshire")
    ABERDEENSHIRE("Aberdeenshire"),
    @XmlEnumValue("Angus")
    ANGUS("Angus"),
    @XmlEnumValue("ArgyllAndBute")
    ARGYLL_AND_BUTE("ArgyllAndBute"),
    @XmlEnumValue("BathAndNorthEastSomerset")
    BATH_AND_NORTH_EAST_SOMERSET("BathAndNorthEastSomerset"),
    @XmlEnumValue("Bedfordshire")
    BEDFORDSHIRE("Bedfordshire"),
    @XmlEnumValue("Bedford")
    BEDFORD("Bedford"),
    @XmlEnumValue("CentralBedfordshire")
    CENTRAL_BEDFORDSHIRE("CentralBedfordshire"),
    @XmlEnumValue("Berkshire")
    BERKSHIRE("Berkshire"),
    @XmlEnumValue("BlackburnWithDarwen")
    BLACKBURN_WITH_DARWEN("BlackburnWithDarwen"),
    @XmlEnumValue("Blackpool")
    BLACKPOOL("Blackpool"),
    @XmlEnumValue("BlaenauGwent")
    BLAENAU_GWENT("BlaenauGwent"),
    @XmlEnumValue("Bournemouth")
    BOURNEMOUTH("Bournemouth"),
    @XmlEnumValue("BracknellForest")
    BRACKNELL_FOREST("BracknellForest"),
    @XmlEnumValue("Bridgend")
    BRIDGEND("Bridgend"),
    @XmlEnumValue("BrightonAndHove")
    BRIGHTON_AND_HOVE("BrightonAndHove"),
    @XmlEnumValue("Bristol")
    BRISTOL("Bristol"),
    @XmlEnumValue("Buckinghamshire")
    BUCKINGHAMSHIRE("Buckinghamshire"),
    @XmlEnumValue("Caerphilly")
    CAERPHILLY("Caerphilly"),
    @XmlEnumValue("Cambridgeshire")
    CAMBRIDGESHIRE("Cambridgeshire"),
    @XmlEnumValue("Cardiff")
    CARDIFF("Cardiff"),
    @XmlEnumValue("Carmarthenshire")
    CARMARTHENSHIRE("Carmarthenshire"),
    @XmlEnumValue("CentroWestMidlands")
    CENTRO_WEST_MIDLANDS("CentroWestMidlands"),
    @XmlEnumValue("Ceredigion")
    CEREDIGION("Ceredigion"),
    @XmlEnumValue("ChannelIslands")
    CHANNEL_ISLANDS("ChannelIslands"),
    @XmlEnumValue("Cheshire")
    CHESHIRE("Cheshire"),
    @XmlEnumValue("CheshireEast")
    CHESHIRE_EAST("CheshireEast"),
    @XmlEnumValue("CheshireWestAndChester")
    CHESHIRE_WEST_AND_CHESTER("CheshireWestAndChester"),
    @XmlEnumValue("CheshireWestAndCheshire")
    CHESHIRE_WEST_AND_CHESHIRE("CheshireWestAndCheshire"),
    @XmlEnumValue("Clackmannanshire")
    CLACKMANNANSHIRE("Clackmannanshire"),
    @XmlEnumValue("ComhairleNanEileanSiar")
    COMHAIRLE_NAN_EILEAN_SIAR("ComhairleNanEileanSiar"),
    @XmlEnumValue("Conwy")
    CONWY("Conwy"),
    @XmlEnumValue("CornwallAndScillies")
    CORNWALL_AND_SCILLIES("CornwallAndScillies"),
    @XmlEnumValue("Cumbria")
    CUMBRIA("Cumbria"),
    @XmlEnumValue("Darlington")
    DARLINGTON("Darlington"),
    @XmlEnumValue("Denbighshire")
    DENBIGHSHIRE("Denbighshire"),
    @XmlEnumValue("Derby")
    DERBY("Derby"),
    @XmlEnumValue("Derbyshire")
    DERBYSHIRE("Derbyshire"),
    @XmlEnumValue("Devon")
    DEVON("Devon"),
    @XmlEnumValue("Dorset")
    DORSET("Dorset"),
    @XmlEnumValue("DumfriesAndGalloway")
    DUMFRIES_AND_GALLOWAY("DumfriesAndGalloway"),
    @XmlEnumValue("Dundee")
    DUNDEE("Dundee"),
    @XmlEnumValue("Durham")
    DURHAM("Durham"),
    @XmlEnumValue("EastAyrshire")
    EAST_AYRSHIRE("EastAyrshire"),
    @XmlEnumValue("EastDunbartonshire")
    EAST_DUNBARTONSHIRE("EastDunbartonshire"),
    @XmlEnumValue("EastLothian")
    EAST_LOTHIAN("EastLothian"),
    @XmlEnumValue("EastRenfrewshire")
    EAST_RENFREWSHIRE("EastRenfrewshire"),
    @XmlEnumValue("EastRidingOfYorkshire")
    EAST_RIDING_OF_YORKSHIRE("EastRidingOfYorkshire"),
    @XmlEnumValue("EastSussex")
    EAST_SUSSEX("EastSussex"),
    @XmlEnumValue("Edinburgh")
    EDINBURGH("Edinburgh"),
    @XmlEnumValue("Essex")
    ESSEX("Essex"),
    @XmlEnumValue("Falkirk")
    FALKIRK("Falkirk"),
    @XmlEnumValue("Fife")
    FIFE("Fife"),
    @XmlEnumValue("Flintshire")
    FLINTSHIRE("Flintshire"),
    @XmlEnumValue("Glasgow")
    GLASGOW("Glasgow"),
    @XmlEnumValue("Gloucestershire")
    GLOUCESTERSHIRE("Gloucestershire"),
    GMPTE("GMPTE"),
    @XmlEnumValue("Gwynedd")
    GWYNEDD("Gwynedd"),
    @XmlEnumValue("Halton")
    HALTON("Halton"),
    @XmlEnumValue("Hampshire")
    HAMPSHIRE("Hampshire"),
    @XmlEnumValue("Hartlepool")
    HARTLEPOOL("Hartlepool"),
    @XmlEnumValue("Havering")
    HAVERING("Havering"),
    @XmlEnumValue("Herefordshire")
    HEREFORDSHIRE("Herefordshire"),
    @XmlEnumValue("Hertfordshire")
    HERTFORDSHIRE("Hertfordshire"),
    @XmlEnumValue("Highland")
    HIGHLAND("Highland"),
    @XmlEnumValue("Inverclyde")
    INVERCLYDE("Inverclyde"),
    @XmlEnumValue("IsleOfAnglesey")
    ISLE_OF_ANGLESEY("IsleOfAnglesey"),
    @XmlEnumValue("IsleOfMan")
    ISLE_OF_MAN("IsleOfMan"),
    @XmlEnumValue("IsleOfWight")
    ISLE_OF_WIGHT("IsleOfWight"),
    @XmlEnumValue("Kent")
    KENT("Kent"),
    @XmlEnumValue("KingstonUponHull")
    KINGSTON_UPON_HULL("KingstonUponHull"),
    @XmlEnumValue("Lancashire")
    LANCASHIRE("Lancashire"),
    @XmlEnumValue("Leicester")
    LEICESTER("Leicester"),
    @XmlEnumValue("Leicestershire")
    LEICESTERSHIRE("Leicestershire"),
    @XmlEnumValue("Lincolnshire")
    LINCOLNSHIRE("Lincolnshire"),
    @XmlEnumValue("London")
    LONDON("London"),
    @XmlEnumValue("Luton")
    LUTON("Luton"),
    @XmlEnumValue("Medway")
    MEDWAY("Medway"),
    @XmlEnumValue("Merseytravel")
    MERSEYTRAVEL("Merseytravel"),
    @XmlEnumValue("MerthyrTydfil")
    MERTHYR_TYDFIL("MerthyrTydfil"),
    @XmlEnumValue("Metro")
    METRO("Metro"),
    @XmlEnumValue("Middlesbrough")
    MIDDLESBROUGH("Middlesbrough"),
    @XmlEnumValue("Midlothian")
    MIDLOTHIAN("Midlothian"),
    @XmlEnumValue("MiltonKeynes")
    MILTON_KEYNES("MiltonKeynes"),
    @XmlEnumValue("Monmouthshire")
    MONMOUTHSHIRE("Monmouthshire"),
    @XmlEnumValue("Moray")
    MORAY("Moray"),
    @XmlEnumValue("NeathPortTalbot")
    NEATH_PORT_TALBOT("NeathPortTalbot"),
    @XmlEnumValue("Newport")
    NEWPORT("Newport"),
    @XmlEnumValue("NexusTynesde")
    NEXUS_TYNESDE("NexusTynesde"),
    @XmlEnumValue("Norfolk")
    NORFOLK("Norfolk"),
    @XmlEnumValue("NorthAyrshire")
    NORTH_AYRSHIRE("NorthAyrshire"),
    @XmlEnumValue("NorthEastLincolnshire")
    NORTH_EAST_LINCOLNSHIRE("NorthEastLincolnshire"),
    @XmlEnumValue("NorthLanarkshire")
    NORTH_LANARKSHIRE("NorthLanarkshire"),
    @XmlEnumValue("NorthLincolnshire")
    NORTH_LINCOLNSHIRE("NorthLincolnshire"),
    @XmlEnumValue("NorthernIreland")
    NORTHERN_IRELAND("NorthernIreland"),
    @XmlEnumValue("NorthSomerset")
    NORTH_SOMERSET("NorthSomerset"),
    @XmlEnumValue("NorthYorkshire")
    NORTH_YORKSHIRE("NorthYorkshire"),
    @XmlEnumValue("Northamptonshire")
    NORTHAMPTONSHIRE("Northamptonshire"),
    @XmlEnumValue("Northumberland")
    NORTHUMBERLAND("Northumberland"),
    @XmlEnumValue("Nottingham")
    NOTTINGHAM("Nottingham"),
    @XmlEnumValue("Nottinghamshire")
    NOTTINGHAMSHIRE("Nottinghamshire"),
    @XmlEnumValue("OrkneyIslands")
    ORKNEY_ISLANDS("OrkneyIslands"),
    @XmlEnumValue("Oxfordshire")
    OXFORDSHIRE("Oxfordshire"),
    @XmlEnumValue("Pembrokeshire")
    PEMBROKESHIRE("Pembrokeshire"),
    @XmlEnumValue("PerthAndKinross")
    PERTH_AND_KINROSS("PerthAndKinross"),
    @XmlEnumValue("Peterborough")
    PETERBOROUGH("Peterborough"),
    @XmlEnumValue("Plymouth")
    PLYMOUTH("Plymouth"),
    @XmlEnumValue("Poole")
    POOLE("Poole"),
    @XmlEnumValue("Portsmouth")
    PORTSMOUTH("Portsmouth"),
    @XmlEnumValue("Powys")
    POWYS("Powys"),
    @XmlEnumValue("Reading")
    READING("Reading"),
    @XmlEnumValue("RedcarAndCleveland")
    REDCAR_AND_CLEVELAND("RedcarAndCleveland"),
    @XmlEnumValue("Renfrewshire")
    RENFREWSHIRE("Renfrewshire"),
    @XmlEnumValue("RhonddaCynonTaff")
    RHONDDA_CYNON_TAFF("RhonddaCynonTaff"),
    @XmlEnumValue("Rutland")
    RUTLAND("Rutland"),
    @XmlEnumValue("ScottishBorders")
    SCOTTISH_BORDERS("ScottishBorders"),
    @XmlEnumValue("ShetlandIslands")
    SHETLAND_ISLANDS("ShetlandIslands"),
    @XmlEnumValue("Shropshire")
    SHROPSHIRE("Shropshire"),
    @XmlEnumValue("Slough")
    SLOUGH("Slough"),
    @XmlEnumValue("Somerset")
    SOMERSET("Somerset"),
    @XmlEnumValue("SouthAyrshire")
    SOUTH_AYRSHIRE("SouthAyrshire"),
    @XmlEnumValue("SouthGloucestershire")
    SOUTH_GLOUCESTERSHIRE("SouthGloucestershire"),
    @XmlEnumValue("SouthLanarkshire")
    SOUTH_LANARKSHIRE("SouthLanarkshire"),
    @XmlEnumValue("SouthYorkshirePTE")
    SOUTH_YORKSHIRE_PTE("SouthYorkshirePTE"),
    @XmlEnumValue("Southampton")
    SOUTHAMPTON("Southampton"),
    @XmlEnumValue("SouthendOnSea")
    SOUTHEND_ON_SEA("SouthendOnSea"),
    @XmlEnumValue("Staffordshire")
    STAFFORDSHIRE("Staffordshire"),
    @XmlEnumValue("Stirling")
    STIRLING("Stirling"),
    @XmlEnumValue("StocktonOnTees")
    STOCKTON_ON_TEES("StocktonOnTees"),
    @XmlEnumValue("StokeOnTrent")
    STOKE_ON_TRENT("StokeOnTrent"),
    @XmlEnumValue("StrathclydePTE")
    STRATHCLYDE_PTE("StrathclydePTE"),
    @XmlEnumValue("Suffolk")
    SUFFOLK("Suffolk"),
    @XmlEnumValue("Surrey")
    SURREY("Surrey"),
    @XmlEnumValue("Swansea")
    SWANSEA("Swansea"),
    @XmlEnumValue("Swindon")
    SWINDON("Swindon"),
    @XmlEnumValue("TelfordAndWrekin")
    TELFORD_AND_WREKIN("TelfordAndWrekin"),
    @XmlEnumValue("Thurrock")
    THURROCK("Thurrock"),
    @XmlEnumValue("Torbay")
    TORBAY("Torbay"),
    @XmlEnumValue("Torfaen")
    TORFAEN("Torfaen"),
    @XmlEnumValue("Translink")
    TRANSLINK("Translink"),
    @XmlEnumValue("ValeOfGlamorgan")
    VALE_OF_GLAMORGAN("ValeOfGlamorgan"),
    @XmlEnumValue("Warrington")
    WARRINGTON("Warrington"),
    @XmlEnumValue("Warwickshire")
    WARWICKSHIRE("Warwickshire"),
    @XmlEnumValue("WestBerkshire")
    WEST_BERKSHIRE("WestBerkshire"),
    @XmlEnumValue("WestDunbartonshire")
    WEST_DUNBARTONSHIRE("WestDunbartonshire"),
    @XmlEnumValue("WestLothian")
    WEST_LOTHIAN("WestLothian"),
    @XmlEnumValue("WestSussex")
    WEST_SUSSEX("WestSussex"),
    @XmlEnumValue("Wiltshire")
    WILTSHIRE("Wiltshire"),
    @XmlEnumValue("WindsorAndMaidenhead")
    WINDSOR_AND_MAIDENHEAD("WindsorAndMaidenhead"),
    @XmlEnumValue("Wokingham")
    WOKINGHAM("Wokingham"),
    @XmlEnumValue("Worcestershire")
    WORCESTERSHIRE("Worcestershire"),
    @XmlEnumValue("Wrexham")
    WREXHAM("Wrexham"),
    @XmlEnumValue("York")
    YORK("York");
    private final String value;

    AuthorityNameEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AuthorityNameEnumeration fromValue(String v) {
        for (AuthorityNameEnumeration c: AuthorityNameEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
