//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Whether a change to a service does or does not exceed the allowed limit, and is thus considered to be major/minor change. Applies only to short notice registrations.
 * 
 * <p>Java class for ChangeImpactStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeImpactStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ChangeExceedsLimit">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ChangeDoesNotExceedLimit">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MinorChangeDescription" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeImpactStructure", propOrder = {
    "changeExceedsLimit",
    "changeDoesNotExceedLimit"
})
public class ChangeImpactStructure {

    @XmlElement(name = "ChangeExceedsLimit")
    protected ChangeImpactStructure.ChangeExceedsLimit changeExceedsLimit;
    @XmlElement(name = "ChangeDoesNotExceedLimit")
    protected ChangeImpactStructure.ChangeDoesNotExceedLimit changeDoesNotExceedLimit;

    /**
     * Gets the value of the changeExceedsLimit property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeImpactStructure.ChangeExceedsLimit }
     *     
     */
    public ChangeImpactStructure.ChangeExceedsLimit getChangeExceedsLimit() {
        return changeExceedsLimit;
    }

    /**
     * Sets the value of the changeExceedsLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeImpactStructure.ChangeExceedsLimit }
     *     
     */
    public void setChangeExceedsLimit(ChangeImpactStructure.ChangeExceedsLimit value) {
        this.changeExceedsLimit = value;
    }

    /**
     * Gets the value of the changeDoesNotExceedLimit property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeImpactStructure.ChangeDoesNotExceedLimit }
     *     
     */
    public ChangeImpactStructure.ChangeDoesNotExceedLimit getChangeDoesNotExceedLimit() {
        return changeDoesNotExceedLimit;
    }

    /**
     * Sets the value of the changeDoesNotExceedLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeImpactStructure.ChangeDoesNotExceedLimit }
     *     
     */
    public void setChangeDoesNotExceedLimit(ChangeImpactStructure.ChangeDoesNotExceedLimit value) {
        this.changeDoesNotExceedLimit = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MinorChangeDescription" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "minorChangeDescription"
    })
    public static class ChangeDoesNotExceedLimit {

        @XmlElement(name = "MinorChangeDescription", required = true)
        protected NaturalLanguageStringStructure minorChangeDescription;

        /**
         * Gets the value of the minorChangeDescription property.
         * 
         * @return
         *     possible object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public NaturalLanguageStringStructure getMinorChangeDescription() {
            return minorChangeDescription;
        }

        /**
         * Sets the value of the minorChangeDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public void setMinorChangeDescription(NaturalLanguageStringStructure value) {
            this.minorChangeDescription = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ChangeExceedsLimit {


    }

}
