//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A collection of one or more open-ended date ranges, and any number of date exceptions.
 * 
 * <p>Java class for DatePatternStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatePatternStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateRange" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.transxchange.org.uk/}OpenDateRangeStructure">
 *                 &lt;sequence>
 *                   &lt;element name="Description" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DateExclusion" type="{http://www.transxchange.org.uk/}DateType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatePatternStructure", propOrder = {
    "dateRange",
    "dateExclusion"
})
public class DatePatternStructure {

    @XmlElement(name = "DateRange", required = true)
    protected List<DatePatternStructure.DateRange> dateRange;
    @XmlElement(name = "DateExclusion")
    protected List<XMLGregorianCalendar> dateExclusion;

    /**
     * Gets the value of the dateRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatePatternStructure.DateRange }
     * 
     * 
     */
    public List<DatePatternStructure.DateRange> getDateRange() {
        if (dateRange == null) {
            dateRange = new ArrayList<DatePatternStructure.DateRange>();
        }
        return this.dateRange;
    }

    /**
     * Gets the value of the dateExclusion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateExclusion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateExclusion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getDateExclusion() {
        if (dateExclusion == null) {
            dateExclusion = new ArrayList<XMLGregorianCalendar>();
        }
        return this.dateExclusion;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.transxchange.org.uk/}OpenDateRangeStructure">
     *       &lt;sequence>
     *         &lt;element name="Description" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description"
    })
    public static class DateRange
        extends OpenDateRangeStructure
    {

        @XmlElement(name = "Description")
        protected NaturalLanguageStringStructure description;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public NaturalLanguageStringStructure getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public void setDescription(NaturalLanguageStringStructure value) {
            this.description = value;
        }

    }

}
