//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import uk.gov.govtalk.people.addressandpersonaldetails.UKPostalAddressStructure;


/**
 * Details of an operator's bus garage (or depot).
 * 
 * <p>Java class for GarageStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GarageStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GarageCode" type="{http://www.transxchange.org.uk/}GarageCodeType"/>
 *         &lt;element name="GarageName" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *         &lt;element name="ContactNumber" type="{http://www.transxchange.org.uk/}TelephoneContactStructure" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}UKPostalAddressStructure" minOccurs="0"/>
 *         &lt;element name="Location" type="{http://www.transxchange.org.uk/}LocationStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GarageStructure", propOrder = {
    "garageCode",
    "garageName",
    "contactNumber",
    "address",
    "location"
})
public class GarageStructure {

    @XmlElement(name = "GarageCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String garageCode;
    @XmlElement(name = "GarageName")
    protected NaturalLanguageStringStructure garageName;
    @XmlElement(name = "ContactNumber")
    protected TelephoneContactStructure contactNumber;
    @XmlElement(name = "Address")
    protected UKPostalAddressStructure address;
    @XmlElement(name = "Location")
    protected LocationStructure location;

    /**
     * Gets the value of the garageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGarageCode() {
        return garageCode;
    }

    /**
     * Sets the value of the garageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGarageCode(String value) {
        this.garageCode = value;
    }

    /**
     * Gets the value of the garageName property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getGarageName() {
        return garageName;
    }

    /**
     * Sets the value of the garageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setGarageName(NaturalLanguageStringStructure value) {
        this.garageName = value;
    }

    /**
     * Gets the value of the contactNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TelephoneContactStructure }
     *     
     */
    public TelephoneContactStructure getContactNumber() {
        return contactNumber;
    }

    /**
     * Sets the value of the contactNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephoneContactStructure }
     *     
     */
    public void setContactNumber(TelephoneContactStructure value) {
        this.contactNumber = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link UKPostalAddressStructure }
     *     
     */
    public UKPostalAddressStructure getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link UKPostalAddressStructure }
     *     
     */
    public void setAddress(UKPostalAddressStructure value) {
        this.address = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setLocation(LocationStructure value) {
        this.location = value;
    }

}
