//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * A link between two Stop Points making up a step within a JourneyPattern.
 * 
 * <p>Java class for JourneyPatternTimingLinkStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JourneyPatternTimingLinkStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.transxchange.org.uk/}AbstractTimingLinkStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.transxchange.org.uk/}JourneyPatternTimingLinkGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JourneyPatternTimingLinkStructure", propOrder = {
    "from",
    "to",
    "routeLinkRef",
    "direction",
    "runTime",
    "distance"
})
public class JourneyPatternTimingLinkStructure
    extends AbstractTimingLinkStructure
{

    @XmlElement(name = "From", required = true)
    protected JourneyPatternStopUsageStructure from;
    @XmlElement(name = "To", required = true)
    protected JourneyPatternStopUsageStructure to;
    @XmlElement(name = "RouteLinkRef")
    protected RouteRefStructure routeLinkRef;
    @XmlElement(name = "Direction", defaultValue = "inherit")
    protected JourneyPatternLinkDirectionEnumeration direction;
    @XmlElement(name = "RunTime", required = true)
    protected Duration runTime;
    @XmlElement(name = "Distance")
    protected BigInteger distance;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyPatternStopUsageStructure }
     *     
     */
    public JourneyPatternStopUsageStructure getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyPatternStopUsageStructure }
     *     
     */
    public void setFrom(JourneyPatternStopUsageStructure value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyPatternStopUsageStructure }
     *     
     */
    public JourneyPatternStopUsageStructure getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyPatternStopUsageStructure }
     *     
     */
    public void setTo(JourneyPatternStopUsageStructure value) {
        this.to = value;
    }

    /**
     * Gets the value of the routeLinkRef property.
     * 
     * @return
     *     possible object is
     *     {@link RouteRefStructure }
     *     
     */
    public RouteRefStructure getRouteLinkRef() {
        return routeLinkRef;
    }

    /**
     * Sets the value of the routeLinkRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteRefStructure }
     *     
     */
    public void setRouteLinkRef(RouteRefStructure value) {
        this.routeLinkRef = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyPatternLinkDirectionEnumeration }
     *     
     */
    public JourneyPatternLinkDirectionEnumeration getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyPatternLinkDirectionEnumeration }
     *     
     */
    public void setDirection(JourneyPatternLinkDirectionEnumeration value) {
        this.direction = value;
    }

    /**
     * Gets the value of the runTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getRunTime() {
        return runTime;
    }

    /**
     * Sets the value of the runTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setRunTime(Duration value) {
        this.runTime = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDistance(BigInteger value) {
        this.distance = value;
    }

}
