//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Reference to a Journey Pattern and a stop within it.
 * 
 * <p>Java class for JourneyPatternUsageRefStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JourneyPatternUsageRefStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JourneyPatternRef" type="{http://www.transxchange.org.uk/}JourneyPatternRefStructure"/>
 *         &lt;element name="StopUsageRef" type="{http://www.transxchange.org.uk/}StopUsageRefStructure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JourneyPatternUsageRefStructure", propOrder = {
    "journeyPatternRef",
    "stopUsageRef"
})
public class JourneyPatternUsageRefStructure {

    @XmlElement(name = "JourneyPatternRef", required = true)
    protected JourneyPatternRefStructure journeyPatternRef;
    @XmlElement(name = "StopUsageRef", required = true)
    protected StopUsageRefStructure stopUsageRef;

    /**
     * Gets the value of the journeyPatternRef property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyPatternRefStructure }
     *     
     */
    public JourneyPatternRefStructure getJourneyPatternRef() {
        return journeyPatternRef;
    }

    /**
     * Sets the value of the journeyPatternRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyPatternRefStructure }
     *     
     */
    public void setJourneyPatternRef(JourneyPatternRefStructure value) {
        this.journeyPatternRef = value;
    }

    /**
     * Gets the value of the stopUsageRef property.
     * 
     * @return
     *     possible object is
     *     {@link StopUsageRefStructure }
     *     
     */
    public StopUsageRefStructure getStopUsageRef() {
        return stopUsageRef;
    }

    /**
     * Sets the value of the stopUsageRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopUsageRefStructure }
     *     
     */
    public void setStopUsageRef(StopUsageRefStructure value) {
        this.stopUsageRef = value;
    }

}
