//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.org.transxchange package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LocationSystem_QNAME = new QName("http://www.transxchange.org.uk/", "LocationSystem");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.org.transxchange
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StopClassificationStructure }
     * 
     */
    public StopClassificationStructure createStopClassificationStructure() {
        return new StopClassificationStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet }
     * 
     */
    public StopClassificationStructure.OffStreet createStopClassificationStructureOffStreet() {
        return new StopClassificationStructure.OffStreet();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.BusAndCoach }
     * 
     */
    public StopClassificationStructure.OffStreet.BusAndCoach createStopClassificationStructureOffStreetBusAndCoach() {
        return new StopClassificationStructure.OffStreet.BusAndCoach();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet }
     * 
     */
    public StopClassificationStructure.OnStreet createStopClassificationStructureOnStreet() {
        return new StopClassificationStructure.OnStreet();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet.Bus }
     * 
     */
    public StopClassificationStructure.OnStreet.Bus createStopClassificationStructureOnStreetBus() {
        return new StopClassificationStructure.OnStreet.Bus();
    }

    /**
     * Create an instance of {@link PublicAvailabilityStructure }
     * 
     */
    public PublicAvailabilityStructure createPublicAvailabilityStructure() {
        return new PublicAvailabilityStructure();
    }

    /**
     * Create an instance of {@link AbstractServicePatternStructure }
     * 
     */
    public AbstractServicePatternStructure createAbstractServicePatternStructure() {
        return new AbstractServicePatternStructure();
    }

    /**
     * Create an instance of {@link AbstractVehicleJourneyStructure }
     * 
     */
    public AbstractVehicleJourneyStructure createAbstractVehicleJourneyStructure() {
        return new AbstractVehicleJourneyStructure();
    }

    /**
     * Create an instance of {@link AbstractServicePatternStructure.Operational }
     * 
     */
    public AbstractServicePatternStructure.Operational createAbstractServicePatternStructureOperational() {
        return new AbstractServicePatternStructure.Operational();
    }

    /**
     * Create an instance of {@link StopPointStructure }
     * 
     */
    public StopPointStructure createStopPointStructure() {
        return new StopPointStructure();
    }

    /**
     * Create an instance of {@link StopPointStructure.Place }
     * 
     */
    public StopPointStructure.Place createStopPointStructurePlace() {
        return new StopPointStructure.Place();
    }

    /**
     * Create an instance of {@link LocationStructure }
     * 
     */
    public LocationStructure createLocationStructure() {
        return new LocationStructure();
    }

    /**
     * Create an instance of {@link StopPointStructure.AlternativeDescriptors }
     * 
     */
    public StopPointStructure.AlternativeDescriptors createStopPointStructureAlternativeDescriptors() {
        return new StopPointStructure.AlternativeDescriptors();
    }

    /**
     * Create an instance of {@link SubsidyDetailsStructure }
     * 
     */
    public SubsidyDetailsStructure createSubsidyDetailsStructure() {
        return new SubsidyDetailsStructure();
    }

    /**
     * Create an instance of {@link RegistrationStructure }
     * 
     */
    public RegistrationStructure createRegistrationStructure() {
        return new RegistrationStructure();
    }

    /**
     * Create an instance of {@link InterchangeLinkStructure }
     * 
     */
    public InterchangeLinkStructure createInterchangeLinkStructure() {
        return new InterchangeLinkStructure();
    }

    /**
     * Create an instance of {@link InterchangeLinkStructure.Accessibility }
     * 
     */
    public InterchangeLinkStructure.Accessibility createInterchangeLinkStructureAccessibility() {
        return new InterchangeLinkStructure.Accessibility();
    }

    /**
     * Create an instance of {@link DatePatternStructure }
     * 
     */
    public DatePatternStructure createDatePatternStructure() {
        return new DatePatternStructure();
    }

    /**
     * Create an instance of {@link BankHolidaysStructure }
     * 
     */
    public BankHolidaysStructure createBankHolidaysStructure() {
        return new BankHolidaysStructure();
    }

    /**
     * Create an instance of {@link ChangeImpactStructure }
     * 
     */
    public ChangeImpactStructure createChangeImpactStructure() {
        return new ChangeImpactStructure();
    }

    /**
     * Create an instance of {@link StopValidityStructure }
     * 
     */
    public StopValidityStructure createStopValidityStructure() {
        return new StopValidityStructure();
    }

    /**
     * Create an instance of {@link DayAndTimeAvailabilityStructure }
     * 
     */
    public DayAndTimeAvailabilityStructure createDayAndTimeAvailabilityStructure() {
        return new DayAndTimeAvailabilityStructure();
    }

    /**
     * Create an instance of {@link ServiceStructure }
     * 
     */
    public ServiceStructure createServiceStructure() {
        return new ServiceStructure();
    }

    /**
     * Create an instance of {@link ServiceStructure.Lines }
     * 
     */
    public ServiceStructure.Lines createServiceStructureLines() {
        return new ServiceStructure.Lines();
    }

    /**
     * Create an instance of {@link RegularOperationStructure }
     * 
     */
    public RegularOperationStructure createRegularOperationStructure() {
        return new RegularOperationStructure();
    }

    /**
     * Create an instance of {@link FlexibleJourneyPatternStructure }
     * 
     */
    public FlexibleJourneyPatternStructure createFlexibleJourneyPatternStructure() {
        return new FlexibleJourneyPatternStructure();
    }

    /**
     * Create an instance of {@link DeadRunStructure }
     * 
     */
    public DeadRunStructure createDeadRunStructure() {
        return new DeadRunStructure();
    }

    /**
     * Create an instance of {@link ServiceClassificationStructure }
     * 
     */
    public ServiceClassificationStructure createServiceClassificationStructure() {
        return new ServiceClassificationStructure();
    }

    /**
     * Create an instance of {@link StandardServiceStructure }
     * 
     */
    public StandardServiceStructure createStandardServiceStructure() {
        return new StandardServiceStructure();
    }

    /**
     * Create an instance of {@link TrackInstructionsStructure }
     * 
     */
    public TrackInstructionsStructure createTrackInstructionsStructure() {
        return new TrackInstructionsStructure();
    }

    /**
     * Create an instance of {@link FrequentServiceStructure }
     * 
     */
    public FrequentServiceStructure createFrequentServiceStructure() {
        return new FrequentServiceStructure();
    }

    /**
     * Create an instance of {@link StopRequirementsStructure }
     * 
     */
    public StopRequirementsStructure createStopRequirementsStructure() {
        return new StopRequirementsStructure();
    }

    /**
     * Create an instance of {@link VehicleJourneysStructure }
     * 
     */
    public VehicleJourneysStructure createVehicleJourneysStructure() {
        return new VehicleJourneysStructure();
    }

    /**
     * Create an instance of {@link RouteSectionsStructure }
     * 
     */
    public RouteSectionsStructure createRouteSectionsStructure() {
        return new RouteSectionsStructure();
    }

    /**
     * Create an instance of {@link RouteSectionsStructure.RouteSection }
     * 
     */
    public RouteSectionsStructure.RouteSection createRouteSectionsStructureRouteSection() {
        return new RouteSectionsStructure.RouteSection();
    }

    /**
     * Create an instance of {@link TransXChange }
     * 
     */
    public TransXChange createTransXChange() {
        return new TransXChange();
    }

    /**
     * Create an instance of {@link ServicedOrganisationsStructure }
     * 
     */
    public ServicedOrganisationsStructure createServicedOrganisationsStructure() {
        return new ServicedOrganisationsStructure();
    }

    /**
     * Create an instance of {@link TransXChangeNptgLocalitiesStructure }
     * 
     */
    public TransXChangeNptgLocalitiesStructure createTransXChangeNptgLocalitiesStructure() {
        return new TransXChangeNptgLocalitiesStructure();
    }

    /**
     * Create an instance of {@link TransXChangeStopPointsStructure }
     * 
     */
    public TransXChangeStopPointsStructure createTransXChangeStopPointsStructure() {
        return new TransXChangeStopPointsStructure();
    }

    /**
     * Create an instance of {@link StopAreasStructure }
     * 
     */
    public StopAreasStructure createStopAreasStructure() {
        return new StopAreasStructure();
    }

    /**
     * Create an instance of {@link RoutesStructure }
     * 
     */
    public RoutesStructure createRoutesStructure() {
        return new RoutesStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternSectionsStructure }
     * 
     */
    public JourneyPatternSectionsStructure createJourneyPatternSectionsStructure() {
        return new JourneyPatternSectionsStructure();
    }

    /**
     * Create an instance of {@link OperatorsStructure }
     * 
     */
    public OperatorsStructure createOperatorsStructure() {
        return new OperatorsStructure();
    }

    /**
     * Create an instance of {@link ServicesStructure }
     * 
     */
    public ServicesStructure createServicesStructure() {
        return new ServicesStructure();
    }

    /**
     * Create an instance of {@link RegistrationsStructure }
     * 
     */
    public RegistrationsStructure createRegistrationsStructure() {
        return new RegistrationsStructure();
    }

    /**
     * Create an instance of {@link SupportingDocumentsStructure }
     * 
     */
    public SupportingDocumentsStructure createSupportingDocumentsStructure() {
        return new SupportingDocumentsStructure();
    }

    /**
     * Create an instance of {@link PositioningLinkStructure }
     * 
     */
    public PositioningLinkStructure createPositioningLinkStructure() {
        return new PositioningLinkStructure();
    }

    /**
     * Create an instance of {@link AbstractTimingLinkStopUsageStructure }
     * 
     */
    public AbstractTimingLinkStopUsageStructure createAbstractTimingLinkStopUsageStructure() {
        return new AbstractTimingLinkStopUsageStructure();
    }

    /**
     * Create an instance of {@link ServiceRequestStructure }
     * 
     */
    public ServiceRequestStructure createServiceRequestStructure() {
        return new ServiceRequestStructure();
    }

    /**
     * Create an instance of {@link VehicleJourneyStopUsageStructure }
     * 
     */
    public VehicleJourneyStopUsageStructure createVehicleJourneyStopUsageStructure() {
        return new VehicleJourneyStopUsageStructure();
    }

    /**
     * Create an instance of {@link PeriodicStructure }
     * 
     */
    public PeriodicStructure createPeriodicStructure() {
        return new PeriodicStructure();
    }

    /**
     * Create an instance of {@link ServiceRefStructure }
     * 
     */
    public ServiceRefStructure createServiceRefStructure() {
        return new ServiceRefStructure();
    }

    /**
     * Create an instance of {@link AdministrativeAreaVersionedRefStructure }
     * 
     */
    public AdministrativeAreaVersionedRefStructure createAdministrativeAreaVersionedRefStructure() {
        return new AdministrativeAreaVersionedRefStructure();
    }

    /**
     * Create an instance of {@link VariableStopAllocationsStructure }
     * 
     */
    public VariableStopAllocationsStructure createVariableStopAllocationsStructure() {
        return new VariableStopAllocationsStructure();
    }

    /**
     * Create an instance of {@link RegionRefsStructure }
     * 
     */
    public RegionRefsStructure createRegionRefsStructure() {
        return new RegionRefsStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternInterchangeRefStructure }
     * 
     */
    public JourneyPatternInterchangeRefStructure createJourneyPatternInterchangeRefStructure() {
        return new JourneyPatternInterchangeRefStructure();
    }

    /**
     * Create an instance of {@link PositioningLinkUsageStructure }
     * 
     */
    public PositioningLinkUsageStructure createPositioningLinkUsageStructure() {
        return new PositioningLinkUsageStructure();
    }

    /**
     * Create an instance of {@link BearingStructure }
     * 
     */
    public BearingStructure createBearingStructure() {
        return new BearingStructure();
    }

    /**
     * Create an instance of {@link GaragesStructure }
     * 
     */
    public GaragesStructure createGaragesStructure() {
        return new GaragesStructure();
    }

    /**
     * Create an instance of {@link PlusbusZoneRefsStructure }
     * 
     */
    public PlusbusZoneRefsStructure createPlusbusZoneRefsStructure() {
        return new PlusbusZoneRefsStructure();
    }

    /**
     * Create an instance of {@link ExceptionalRequirementStructure }
     * 
     */
    public ExceptionalRequirementStructure createExceptionalRequirementStructure() {
        return new ExceptionalRequirementStructure();
    }

    /**
     * Create an instance of {@link ChangeRequestedByExternalAuthorityStructure }
     * 
     */
    public ChangeRequestedByExternalAuthorityStructure createChangeRequestedByExternalAuthorityStructure() {
        return new ChangeRequestedByExternalAuthorityStructure();
    }

    /**
     * Create an instance of {@link ServicedOrganisationStructure }
     * 
     */
    public ServicedOrganisationStructure createServicedOrganisationStructure() {
        return new ServicedOrganisationStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternRefStructure }
     * 
     */
    public JourneyPatternRefStructure createJourneyPatternRefStructure() {
        return new JourneyPatternRefStructure();
    }

    /**
     * Create an instance of {@link VosaRegistrationNumberStructure }
     * 
     */
    public VosaRegistrationNumberStructure createVosaRegistrationNumberStructure() {
        return new VosaRegistrationNumberStructure();
    }

    /**
     * Create an instance of {@link GarageRefStructure }
     * 
     */
    public GarageRefStructure createGarageRefStructure() {
        return new GarageRefStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternSectionStructure }
     * 
     */
    public JourneyPatternSectionStructure createJourneyPatternSectionStructure() {
        return new JourneyPatternSectionStructure();
    }

    /**
     * Create an instance of {@link InterchangePathStructure }
     * 
     */
    public InterchangePathStructure createInterchangePathStructure() {
        return new InterchangePathStructure();
    }

    /**
     * Create an instance of {@link LineStringStructure }
     * 
     */
    public LineStringStructure createLineStringStructure() {
        return new LineStringStructure();
    }

    /**
     * Create an instance of {@link ToBeMarketedWithStructure }
     * 
     */
    public ToBeMarketedWithStructure createToBeMarketedWithStructure() {
        return new ToBeMarketedWithStructure();
    }

    /**
     * Create an instance of {@link NptgLocalityRefsStructure }
     * 
     */
    public NptgLocalityRefsStructure createNptgLocalityRefsStructure() {
        return new NptgLocalityRefsStructure();
    }

    /**
     * Create an instance of {@link AbstractJourneyPatternStructure }
     * 
     */
    public AbstractJourneyPatternStructure createAbstractJourneyPatternStructure() {
        return new AbstractJourneyPatternStructure();
    }

    /**
     * Create an instance of {@link AnnotatedClosedDateRangeStructure }
     * 
     */
    public AnnotatedClosedDateRangeStructure createAnnotatedClosedDateRangeStructure() {
        return new AnnotatedClosedDateRangeStructure();
    }

    /**
     * Create an instance of {@link ServicedOrganisationDaysStructure }
     * 
     */
    public ServicedOrganisationDaysStructure createServicedOrganisationDaysStructure() {
        return new ServicedOrganisationDaysStructure();
    }

    /**
     * Create an instance of {@link AuthorityRefStructure }
     * 
     */
    public AuthorityRefStructure createAuthorityRefStructure() {
        return new AuthorityRefStructure();
    }

    /**
     * Create an instance of {@link GridPositionStructure }
     * 
     */
    public GridPositionStructure createGridPositionStructure() {
        return new GridPositionStructure();
    }

    /**
     * Create an instance of {@link OperatorRefsStructure }
     * 
     */
    public OperatorRefsStructure createOperatorRefsStructure() {
        return new OperatorRefsStructure();
    }

    /**
     * Create an instance of {@link TimingLinkRefStructure }
     * 
     */
    public TimingLinkRefStructure createTimingLinkRefStructure() {
        return new TimingLinkRefStructure();
    }

    /**
     * Create an instance of {@link AnnotatedNptgLocalityRefStructure }
     * 
     */
    public AnnotatedNptgLocalityRefStructure createAnnotatedNptgLocalityRefStructure() {
        return new AnnotatedNptgLocalityRefStructure();
    }

    /**
     * Create an instance of {@link NoteStructure }
     * 
     */
    public NoteStructure createNoteStructure() {
        return new NoteStructure();
    }

    /**
     * Create an instance of {@link FlexibleServiceTimesStructure }
     * 
     */
    public FlexibleServiceTimesStructure createFlexibleServiceTimesStructure() {
        return new FlexibleServiceTimesStructure();
    }

    /**
     * Create an instance of {@link ServicedOrganisationRefStructure }
     * 
     */
    public ServicedOrganisationRefStructure createServicedOrganisationRefStructure() {
        return new ServicedOrganisationRefStructure();
    }

    /**
     * Create an instance of {@link ServicedOrganisationOperationStructure }
     * 
     */
    public ServicedOrganisationOperationStructure createServicedOrganisationOperationStructure() {
        return new ServicedOrganisationOperationStructure();
    }

    /**
     * Create an instance of {@link StopPointWrappedRefStructure }
     * 
     */
    public StopPointWrappedRefStructure createStopPointWrappedRefStructure() {
        return new StopPointWrappedRefStructure();
    }

    /**
     * Create an instance of {@link StopAreaRefsStructure }
     * 
     */
    public StopAreaRefsStructure createStopAreaRefsStructure() {
        return new StopAreaRefsStructure();
    }

    /**
     * Create an instance of {@link ClosedDateRangeStructure }
     * 
     */
    public ClosedDateRangeStructure createClosedDateRangeStructure() {
        return new ClosedDateRangeStructure();
    }

    /**
     * Create an instance of {@link NptgLocalityRefStructure }
     * 
     */
    public NptgLocalityRefStructure createNptgLocalityRefStructure() {
        return new NptgLocalityRefStructure();
    }

    /**
     * Create an instance of {@link AnnotatedClosedDateRangeCollectionStructure }
     * 
     */
    public AnnotatedClosedDateRangeCollectionStructure createAnnotatedClosedDateRangeCollectionStructure() {
        return new AnnotatedClosedDateRangeCollectionStructure();
    }

    /**
     * Create an instance of {@link PlusbusZoneRefStructure }
     * 
     */
    public PlusbusZoneRefStructure createPlusbusZoneRefStructure() {
        return new PlusbusZoneRefStructure();
    }

    /**
     * Create an instance of {@link WeekOfMonthStructure }
     * 
     */
    public WeekOfMonthStructure createWeekOfMonthStructure() {
        return new WeekOfMonthStructure();
    }

    /**
     * Create an instance of {@link OperatorStructure }
     * 
     */
    public OperatorStructure createOperatorStructure() {
        return new OperatorStructure();
    }

    /**
     * Create an instance of {@link DayFrequencyStructure }
     * 
     */
    public DayFrequencyStructure createDayFrequencyStructure() {
        return new DayFrequencyStructure();
    }

    /**
     * Create an instance of {@link NaturalLanguageStringStructure }
     * 
     */
    public NaturalLanguageStringStructure createNaturalLanguageStringStructure() {
        return new NaturalLanguageStringStructure();
    }

    /**
     * Create an instance of {@link PlaceRefStructure }
     * 
     */
    public PlaceRefStructure createPlaceRefStructure() {
        return new PlaceRefStructure();
    }

    /**
     * Create an instance of {@link HalfOpenDateRangeStructure }
     * 
     */
    public HalfOpenDateRangeStructure createHalfOpenDateRangeStructure() {
        return new HalfOpenDateRangeStructure();
    }

    /**
     * Create an instance of {@link FlexibleJourneyPatternStopUsageStructure }
     * 
     */
    public FlexibleJourneyPatternStopUsageStructure createFlexibleJourneyPatternStopUsageStructure() {
        return new FlexibleJourneyPatternStopUsageStructure();
    }

    /**
     * Create an instance of {@link StopPointRefStructure }
     * 
     */
    public StopPointRefStructure createStopPointRefStructure() {
        return new StopPointRefStructure();
    }

    /**
     * Create an instance of {@link OperatorAddressesStructure }
     * 
     */
    public OperatorAddressesStructure createOperatorAddressesStructure() {
        return new OperatorAddressesStructure();
    }

    /**
     * Create an instance of {@link BankHolidayOperationStructure }
     * 
     */
    public BankHolidayOperationStructure createBankHolidayOperationStructure() {
        return new BankHolidayOperationStructure();
    }

    /**
     * Create an instance of {@link TelephoneContactStructure }
     * 
     */
    public TelephoneContactStructure createTelephoneContactStructure() {
        return new TelephoneContactStructure();
    }

    /**
     * Create an instance of {@link FlexibleServiceStructure }
     * 
     */
    public FlexibleServiceStructure createFlexibleServiceStructure() {
        return new FlexibleServiceStructure();
    }

    /**
     * Create an instance of {@link LocalHolidayChangeStructure }
     * 
     */
    public LocalHolidayChangeStructure createLocalHolidayChangeStructure() {
        return new LocalHolidayChangeStructure();
    }

    /**
     * Create an instance of {@link OperatingProfileStructure }
     * 
     */
    public OperatingProfileStructure createOperatingProfileStructure() {
        return new OperatingProfileStructure();
    }

    /**
     * Create an instance of {@link RegionRefStructure }
     * 
     */
    public RegionRefStructure createRegionRefStructure() {
        return new RegionRefStructure();
    }

    /**
     * Create an instance of {@link ReplaceDiscontinuedServiceStructure }
     * 
     */
    public ReplaceDiscontinuedServiceStructure createReplaceDiscontinuedServiceStructure() {
        return new ReplaceDiscontinuedServiceStructure();
    }

    /**
     * Create an instance of {@link VehicleTypeStructure }
     * 
     */
    public VehicleTypeStructure createVehicleTypeStructure() {
        return new VehicleTypeStructure();
    }

    /**
     * Create an instance of {@link MapStructure }
     * 
     */
    public MapStructure createMapStructure() {
        return new MapStructure();
    }

    /**
     * Create an instance of {@link AnnotatedRailRefStructure }
     * 
     */
    public AnnotatedRailRefStructure createAnnotatedRailRefStructure() {
        return new AnnotatedRailRefStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternInterchangeStructure }
     * 
     */
    public JourneyPatternInterchangeStructure createJourneyPatternInterchangeStructure() {
        return new JourneyPatternInterchangeStructure();
    }

    /**
     * Create an instance of {@link NptgLocalityVersionedRefStructure }
     * 
     */
    public NptgLocalityVersionedRefStructure createNptgLocalityVersionedRefStructure() {
        return new NptgLocalityVersionedRefStructure();
    }

    /**
     * Create an instance of {@link FlexibleZoneStructure }
     * 
     */
    public FlexibleZoneStructure createFlexibleZoneStructure() {
        return new FlexibleZoneStructure();
    }

    /**
     * Create an instance of {@link HailAndRideSectionStructure }
     * 
     */
    public HailAndRideSectionStructure createHailAndRideSectionStructure() {
        return new HailAndRideSectionStructure();
    }

    /**
     * Create an instance of {@link NaturalLanguagePlaceNameStructure }
     * 
     */
    public NaturalLanguagePlaceNameStructure createNaturalLanguagePlaceNameStructure() {
        return new NaturalLanguagePlaceNameStructure();
    }

    /**
     * Create an instance of {@link OptionalServiceStructure }
     * 
     */
    public OptionalServiceStructure createOptionalServiceStructure() {
        return new OptionalServiceStructure();
    }

    /**
     * Create an instance of {@link DaysOfOperationStructure }
     * 
     */
    public DaysOfOperationStructure createDaysOfOperationStructure() {
        return new DaysOfOperationStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternStructure }
     * 
     */
    public JourneyPatternStructure createJourneyPatternStructure() {
        return new JourneyPatternStructure();
    }

    /**
     * Create an instance of {@link LineRefStructure }
     * 
     */
    public LineRefStructure createLineRefStructure() {
        return new LineRefStructure();
    }

    /**
     * Create an instance of {@link InterchangeNodeStructure }
     * 
     */
    public InterchangeNodeStructure createInterchangeNodeStructure() {
        return new InterchangeNodeStructure();
    }

    /**
     * Create an instance of {@link VehicleJourneyInterchangeStructure }
     * 
     */
    public VehicleJourneyInterchangeStructure createVehicleJourneyInterchangeStructure() {
        return new VehicleJourneyInterchangeStructure();
    }

    /**
     * Create an instance of {@link RegionVersionedRefStructure }
     * 
     */
    public RegionVersionedRefStructure createRegionVersionedRefStructure() {
        return new RegionVersionedRefStructure();
    }

    /**
     * Create an instance of {@link TrackStructure }
     * 
     */
    public TrackStructure createTrackStructure() {
        return new TrackStructure();
    }

    /**
     * Create an instance of {@link FrequencyStructure }
     * 
     */
    public FrequencyStructure createFrequencyStructure() {
        return new FrequencyStructure();
    }

    /**
     * Create an instance of {@link SpecialOccasionStructure }
     * 
     */
    public SpecialOccasionStructure createSpecialOccasionStructure() {
        return new SpecialOccasionStructure();
    }

    /**
     * Create an instance of {@link TrafficAreaStructure }
     * 
     */
    public TrafficAreaStructure createTrafficAreaStructure() {
        return new TrafficAreaStructure();
    }

    /**
     * Create an instance of {@link ChangeToConnectAlteredServiceStructure }
     * 
     */
    public ChangeToConnectAlteredServiceStructure createChangeToConnectAlteredServiceStructure() {
        return new ChangeToConnectAlteredServiceStructure();
    }

    /**
     * Create an instance of {@link DailyOpeningHoursStructure }
     * 
     */
    public DailyOpeningHoursStructure createDailyOpeningHoursStructure() {
        return new DailyOpeningHoursStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternTimingLinkStructure }
     * 
     */
    public JourneyPatternTimingLinkStructure createJourneyPatternTimingLinkStructure() {
        return new JourneyPatternTimingLinkStructure();
    }

    /**
     * Create an instance of {@link RegulationOrderComplianceStructure }
     * 
     */
    public RegulationOrderComplianceStructure createRegulationOrderComplianceStructure() {
        return new RegulationOrderComplianceStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternStopUsageStructure }
     * 
     */
    public JourneyPatternStopUsageStructure createJourneyPatternStopUsageStructure() {
        return new JourneyPatternStopUsageStructure();
    }

    /**
     * Create an instance of {@link DateCollectionStructure }
     * 
     */
    public DateCollectionStructure createDateCollectionStructure() {
        return new DateCollectionStructure();
    }

    /**
     * Create an instance of {@link VehicleJourneyTimingLinkStructure }
     * 
     */
    public VehicleJourneyTimingLinkStructure createVehicleJourneyTimingLinkStructure() {
        return new VehicleJourneyTimingLinkStructure();
    }

    /**
     * Create an instance of {@link AnnotatedMetroRefStructure }
     * 
     */
    public AnnotatedMetroRefStructure createAnnotatedMetroRefStructure() {
        return new AnnotatedMetroRefStructure();
    }

    /**
     * Create an instance of {@link VehicleJourneyRefStructure }
     * 
     */
    public VehicleJourneyRefStructure createVehicleJourneyRefStructure() {
        return new VehicleJourneyRefStructure();
    }

    /**
     * Create an instance of {@link FlexibleVehicleJourneyStructure }
     * 
     */
    public FlexibleVehicleJourneyStructure createFlexibleVehicleJourneyStructure() {
        return new FlexibleVehicleJourneyStructure();
    }

    /**
     * Create an instance of {@link AdministrativeAreaRefsStructure }
     * 
     */
    public AdministrativeAreaRefsStructure createAdministrativeAreaRefsStructure() {
        return new AdministrativeAreaRefsStructure();
    }

    /**
     * Create an instance of {@link VariableStopAllocationStructure }
     * 
     */
    public VariableStopAllocationStructure createVariableStopAllocationStructure() {
        return new VariableStopAllocationStructure();
    }

    /**
     * Create an instance of {@link PlusbusZoneVersionedRefStructure }
     * 
     */
    public PlusbusZoneVersionedRefStructure createPlusbusZoneVersionedRefStructure() {
        return new PlusbusZoneVersionedRefStructure();
    }

    /**
     * Create an instance of {@link LayoverPointRefStructure }
     * 
     */
    public LayoverPointRefStructure createLayoverPointRefStructure() {
        return new LayoverPointRefStructure();
    }

    /**
     * Create an instance of {@link RouteStructure }
     * 
     */
    public RouteStructure createRouteStructure() {
        return new RouteStructure();
    }

    /**
     * Create an instance of {@link StopAreaWrappedRefStructure }
     * 
     */
    public StopAreaWrappedRefStructure createStopAreaWrappedRefStructure() {
        return new StopAreaWrappedRefStructure();
    }

    /**
     * Create an instance of {@link AbstractTimingLinkStructure }
     * 
     */
    public AbstractTimingLinkStructure createAbstractTimingLinkStructure() {
        return new AbstractTimingLinkStructure();
    }

    /**
     * Create an instance of {@link StopUsageRefStructure }
     * 
     */
    public StopUsageRefStructure createStopUsageRefStructure() {
        return new StopUsageRefStructure();
    }

    /**
     * Create an instance of {@link WGS84PositionStructure }
     * 
     */
    public WGS84PositionStructure createWGS84PositionStructure() {
        return new WGS84PositionStructure();
    }

    /**
     * Create an instance of {@link ServicedOrganisationRefsStructure }
     * 
     */
    public ServicedOrganisationRefsStructure createServicedOrganisationRefsStructure() {
        return new ServicedOrganisationRefsStructure();
    }

    /**
     * Create an instance of {@link RouteRefStructure }
     * 
     */
    public RouteRefStructure createRouteRefStructure() {
        return new RouteRefStructure();
    }

    /**
     * Create an instance of {@link BookingArrangementStructure }
     * 
     */
    public BookingArrangementStructure createBookingArrangementStructure() {
        return new BookingArrangementStructure();
    }

    /**
     * Create an instance of {@link SupportingDocumentStructure }
     * 
     */
    public SupportingDocumentStructure createSupportingDocumentStructure() {
        return new SupportingDocumentStructure();
    }

    /**
     * Create an instance of {@link FullPersonNameStructure }
     * 
     */
    public FullPersonNameStructure createFullPersonNameStructure() {
        return new FullPersonNameStructure();
    }

    /**
     * Create an instance of {@link ModesStructure }
     * 
     */
    public ModesStructure createModesStructure() {
        return new ModesStructure();
    }

    /**
     * Create an instance of {@link AnnotatedStopPointRefStructure }
     * 
     */
    public AnnotatedStopPointRefStructure createAnnotatedStopPointRefStructure() {
        return new AnnotatedStopPointRefStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternSectionRefStructure }
     * 
     */
    public JourneyPatternSectionRefStructure createJourneyPatternSectionRefStructure() {
        return new JourneyPatternSectionRefStructure();
    }

    /**
     * Create an instance of {@link AnnotatedFerryRefStructure }
     * 
     */
    public AnnotatedFerryRefStructure createAnnotatedFerryRefStructure() {
        return new AnnotatedFerryRefStructure();
    }

    /**
     * Create an instance of {@link JourneyPatternUsageRefStructure }
     * 
     */
    public JourneyPatternUsageRefStructure createJourneyPatternUsageRefStructure() {
        return new JourneyPatternUsageRefStructure();
    }

    /**
     * Create an instance of {@link StopPointsStructure }
     * 
     */
    public StopPointsStructure createStopPointsStructure() {
        return new StopPointsStructure();
    }

    /**
     * Create an instance of {@link UniqueServiceStructure }
     * 
     */
    public UniqueServiceStructure createUniqueServiceStructure() {
        return new UniqueServiceStructure();
    }

    /**
     * Create an instance of {@link GarageStructure }
     * 
     */
    public GarageStructure createGarageStructure() {
        return new GarageStructure();
    }

    /**
     * Create an instance of {@link VehicleJourneyStructure }
     * 
     */
    public VehicleJourneyStructure createVehicleJourneyStructure() {
        return new VehicleJourneyStructure();
    }

    /**
     * Create an instance of {@link LicensedOperatorStructure }
     * 
     */
    public LicensedOperatorStructure createLicensedOperatorStructure() {
        return new LicensedOperatorStructure();
    }

    /**
     * Create an instance of {@link OpenDateRangeStructure }
     * 
     */
    public OpenDateRangeStructure createOpenDateRangeStructure() {
        return new OpenDateRangeStructure();
    }

    /**
     * Create an instance of {@link AnnotatedAirRefStructure }
     * 
     */
    public AnnotatedAirRefStructure createAnnotatedAirRefStructure() {
        return new AnnotatedAirRefStructure();
    }

    /**
     * Create an instance of {@link CirculatedAuthoritiesStructure }
     * 
     */
    public CirculatedAuthoritiesStructure createCirculatedAuthoritiesStructure() {
        return new CirculatedAuthoritiesStructure();
    }

    /**
     * Create an instance of {@link StopPointVersionedRefStructure }
     * 
     */
    public StopPointVersionedRefStructure createStopPointVersionedRefStructure() {
        return new StopPointVersionedRefStructure();
    }

    /**
     * Create an instance of {@link ShortNoticeRegistrationStructure }
     * 
     */
    public ShortNoticeRegistrationStructure createShortNoticeRegistrationStructure() {
        return new ShortNoticeRegistrationStructure();
    }

    /**
     * Create an instance of {@link ClosedTimeRangeStructure }
     * 
     */
    public ClosedTimeRangeStructure createClosedTimeRangeStructure() {
        return new ClosedTimeRangeStructure();
    }

    /**
     * Create an instance of {@link MapSystemReferenceStructure }
     * 
     */
    public MapSystemReferenceStructure createMapSystemReferenceStructure() {
        return new MapSystemReferenceStructure();
    }

    /**
     * Create an instance of {@link StopAreaRefStructure }
     * 
     */
    public StopAreaRefStructure createStopAreaRefStructure() {
        return new StopAreaRefStructure();
    }

    /**
     * Create an instance of {@link AnnotatedServiceRefStructure }
     * 
     */
    public AnnotatedServiceRefStructure createAnnotatedServiceRefStructure() {
        return new AnnotatedServiceRefStructure();
    }

    /**
     * Create an instance of {@link StopAreaStructure }
     * 
     */
    public StopAreaStructure createStopAreaStructure() {
        return new StopAreaStructure();
    }

    /**
     * Create an instance of {@link StopPointRefsStructure }
     * 
     */
    public StopPointRefsStructure createStopPointRefsStructure() {
        return new StopPointRefsStructure();
    }

    /**
     * Create an instance of {@link StopAreaVersionedRefStructure }
     * 
     */
    public StopAreaVersionedRefStructure createStopAreaVersionedRefStructure() {
        return new StopAreaVersionedRefStructure();
    }

    /**
     * Create an instance of {@link OperatorRefStructure }
     * 
     */
    public OperatorRefStructure createOperatorRefStructure() {
        return new OperatorRefStructure();
    }

    /**
     * Create an instance of {@link BoundingBoxStructure }
     * 
     */
    public BoundingBoxStructure createBoundingBoxStructure() {
        return new BoundingBoxStructure();
    }

    /**
     * Create an instance of {@link SpecialDaysOperationStructure }
     * 
     */
    public SpecialDaysOperationStructure createSpecialDaysOperationStructure() {
        return new SpecialDaysOperationStructure();
    }

    /**
     * Create an instance of {@link ClosedDateRangeCollectionStructure }
     * 
     */
    public ClosedDateRangeCollectionStructure createClosedDateRangeCollectionStructure() {
        return new ClosedDateRangeCollectionStructure();
    }

    /**
     * Create an instance of {@link TrafficAreasStructure }
     * 
     */
    public TrafficAreasStructure createTrafficAreasStructure() {
        return new TrafficAreasStructure();
    }

    /**
     * Create an instance of {@link AnnotatedCoachRefStructure }
     * 
     */
    public AnnotatedCoachRefStructure createAnnotatedCoachRefStructure() {
        return new AnnotatedCoachRefStructure();
    }

    /**
     * Create an instance of {@link OperatorRoleStructure }
     * 
     */
    public OperatorRoleStructure createOperatorRoleStructure() {
        return new OperatorRoleStructure();
    }

    /**
     * Create an instance of {@link HalfOpenDateTimeRangeStructure }
     * 
     */
    public HalfOpenDateTimeRangeStructure createHalfOpenDateTimeRangeStructure() {
        return new HalfOpenDateTimeRangeStructure();
    }

    /**
     * Create an instance of {@link LayoverPointStructure }
     * 
     */
    public LayoverPointStructure createLayoverPointStructure() {
        return new LayoverPointStructure();
    }

    /**
     * Create an instance of {@link HalfOpenTimeRangeStructure }
     * 
     */
    public HalfOpenTimeRangeStructure createHalfOpenTimeRangeStructure() {
        return new HalfOpenTimeRangeStructure();
    }

    /**
     * Create an instance of {@link AdministrativeAreaRefStructure }
     * 
     */
    public AdministrativeAreaRefStructure createAdministrativeAreaRefStructure() {
        return new AdministrativeAreaRefStructure();
    }

    /**
     * Create an instance of {@link DescriptorStructure }
     * 
     */
    public DescriptorStructure createDescriptorStructure() {
        return new DescriptorStructure();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.Air }
     * 
     */
    public StopClassificationStructure.OffStreet.Air createStopClassificationStructureOffStreetAir() {
        return new StopClassificationStructure.OffStreet.Air();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.Ferry }
     * 
     */
    public StopClassificationStructure.OffStreet.Ferry createStopClassificationStructureOffStreetFerry() {
        return new StopClassificationStructure.OffStreet.Ferry();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.Rail }
     * 
     */
    public StopClassificationStructure.OffStreet.Rail createStopClassificationStructureOffStreetRail() {
        return new StopClassificationStructure.OffStreet.Rail();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.Metro }
     * 
     */
    public StopClassificationStructure.OffStreet.Metro createStopClassificationStructureOffStreetMetro() {
        return new StopClassificationStructure.OffStreet.Metro();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.BusAndCoach.Bay }
     * 
     */
    public StopClassificationStructure.OffStreet.BusAndCoach.Bay createStopClassificationStructureOffStreetBusAndCoachBay() {
        return new StopClassificationStructure.OffStreet.BusAndCoach.Bay();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OffStreet.BusAndCoach.VariableBay }
     * 
     */
    public StopClassificationStructure.OffStreet.BusAndCoach.VariableBay createStopClassificationStructureOffStreetBusAndCoachVariableBay() {
        return new StopClassificationStructure.OffStreet.BusAndCoach.VariableBay();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet.Taxi }
     * 
     */
    public StopClassificationStructure.OnStreet.Taxi createStopClassificationStructureOnStreetTaxi() {
        return new StopClassificationStructure.OnStreet.Taxi();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet.Bus.MarkedPoint }
     * 
     */
    public StopClassificationStructure.OnStreet.Bus.MarkedPoint createStopClassificationStructureOnStreetBusMarkedPoint() {
        return new StopClassificationStructure.OnStreet.Bus.MarkedPoint();
    }

    /**
     * Create an instance of {@link StopClassificationStructure.OnStreet.Bus.UnmarkedPoint }
     * 
     */
    public StopClassificationStructure.OnStreet.Bus.UnmarkedPoint createStopClassificationStructureOnStreetBusUnmarkedPoint() {
        return new StopClassificationStructure.OnStreet.Bus.UnmarkedPoint();
    }

    /**
     * Create an instance of {@link PublicAvailabilityStructure.AvailableToPublic }
     * 
     */
    public PublicAvailabilityStructure.AvailableToPublic createPublicAvailabilityStructureAvailableToPublic() {
        return new PublicAvailabilityStructure.AvailableToPublic();
    }

    /**
     * Create an instance of {@link PublicAvailabilityStructure.NotAvailableToPublic }
     * 
     */
    public PublicAvailabilityStructure.NotAvailableToPublic createPublicAvailabilityStructureNotAvailableToPublic() {
        return new PublicAvailabilityStructure.NotAvailableToPublic();
    }

    /**
     * Create an instance of {@link AbstractServicePatternStructure.LayoverPoint }
     * 
     */
    public AbstractServicePatternStructure.LayoverPoint createAbstractServicePatternStructureLayoverPoint() {
        return new AbstractServicePatternStructure.LayoverPoint();
    }

    /**
     * Create an instance of {@link AbstractVehicleJourneyStructure.VehicleJourneyInterchange }
     * 
     */
    public AbstractVehicleJourneyStructure.VehicleJourneyInterchange createAbstractVehicleJourneyStructureVehicleJourneyInterchange() {
        return new AbstractVehicleJourneyStructure.VehicleJourneyInterchange();
    }

    /**
     * Create an instance of {@link AbstractServicePatternStructure.Operational.Block }
     * 
     */
    public AbstractServicePatternStructure.Operational.Block createAbstractServicePatternStructureOperationalBlock() {
        return new AbstractServicePatternStructure.Operational.Block();
    }

    /**
     * Create an instance of {@link AbstractServicePatternStructure.Operational.TicketMachine }
     * 
     */
    public AbstractServicePatternStructure.Operational.TicketMachine createAbstractServicePatternStructureOperationalTicketMachine() {
        return new AbstractServicePatternStructure.Operational.TicketMachine();
    }

    /**
     * Create an instance of {@link StopPointStructure.Place.Location }
     * 
     */
    public StopPointStructure.Place.Location createStopPointStructurePlaceLocation() {
        return new StopPointStructure.Place.Location();
    }

    /**
     * Create an instance of {@link LocationStructure.Translation }
     * 
     */
    public LocationStructure.Translation createLocationStructureTranslation() {
        return new LocationStructure.Translation();
    }

    /**
     * Create an instance of {@link StopPointStructure.AlternativeDescriptors.Descriptor }
     * 
     */
    public StopPointStructure.AlternativeDescriptors.Descriptor createStopPointStructureAlternativeDescriptorsDescriptor() {
        return new StopPointStructure.AlternativeDescriptors.Descriptor();
    }

    /**
     * Create an instance of {@link SubsidyDetailsStructure.Subsidy }
     * 
     */
    public SubsidyDetailsStructure.Subsidy createSubsidyDetailsStructureSubsidy() {
        return new SubsidyDetailsStructure.Subsidy();
    }

    /**
     * Create an instance of {@link RegistrationStructure.ContractedService }
     * 
     */
    public RegistrationStructure.ContractedService createRegistrationStructureContractedService() {
        return new RegistrationStructure.ContractedService();
    }

    /**
     * Create an instance of {@link InterchangeLinkStructure.Accessibility.Hazard }
     * 
     */
    public InterchangeLinkStructure.Accessibility.Hazard createInterchangeLinkStructureAccessibilityHazard() {
        return new InterchangeLinkStructure.Accessibility.Hazard();
    }

    /**
     * Create an instance of {@link DatePatternStructure.DateRange }
     * 
     */
    public DatePatternStructure.DateRange createDatePatternStructureDateRange() {
        return new DatePatternStructure.DateRange();
    }

    /**
     * Create an instance of {@link BankHolidaysStructure.OtherPublicHoliday }
     * 
     */
    public BankHolidaysStructure.OtherPublicHoliday createBankHolidaysStructureOtherPublicHoliday() {
        return new BankHolidaysStructure.OtherPublicHoliday();
    }

    /**
     * Create an instance of {@link ChangeImpactStructure.ChangeExceedsLimit }
     * 
     */
    public ChangeImpactStructure.ChangeExceedsLimit createChangeImpactStructureChangeExceedsLimit() {
        return new ChangeImpactStructure.ChangeExceedsLimit();
    }

    /**
     * Create an instance of {@link ChangeImpactStructure.ChangeDoesNotExceedLimit }
     * 
     */
    public ChangeImpactStructure.ChangeDoesNotExceedLimit createChangeImpactStructureChangeDoesNotExceedLimit() {
        return new ChangeImpactStructure.ChangeDoesNotExceedLimit();
    }

    /**
     * Create an instance of {@link StopValidityStructure.StopValidity }
     * 
     */
    public StopValidityStructure.StopValidity createStopValidityStructureStopValidity() {
        return new StopValidityStructure.StopValidity();
    }

    /**
     * Create an instance of {@link DayAndTimeAvailabilityStructure.DayTypes }
     * 
     */
    public DayAndTimeAvailabilityStructure.DayTypes createDayAndTimeAvailabilityStructureDayTypes() {
        return new DayAndTimeAvailabilityStructure.DayTypes();
    }

    /**
     * Create an instance of {@link DayAndTimeAvailabilityStructure.Season }
     * 
     */
    public DayAndTimeAvailabilityStructure.Season createDayAndTimeAvailabilityStructureSeason() {
        return new DayAndTimeAvailabilityStructure.Season();
    }

    /**
     * Create an instance of {@link ServiceStructure.ServiceAvailability }
     * 
     */
    public ServiceStructure.ServiceAvailability createServiceStructureServiceAvailability() {
        return new ServiceStructure.ServiceAvailability();
    }

    /**
     * Create an instance of {@link ServiceStructure.JourneyPatternInterchange }
     * 
     */
    public ServiceStructure.JourneyPatternInterchange createServiceStructureJourneyPatternInterchange() {
        return new ServiceStructure.JourneyPatternInterchange();
    }

    /**
     * Create an instance of {@link ServiceStructure.Lines.Line }
     * 
     */
    public ServiceStructure.Lines.Line createServiceStructureLinesLine() {
        return new ServiceStructure.Lines.Line();
    }

    /**
     * Create an instance of {@link RegularOperationStructure.DaysOfWeek }
     * 
     */
    public RegularOperationStructure.DaysOfWeek createRegularOperationStructureDaysOfWeek() {
        return new RegularOperationStructure.DaysOfWeek();
    }

    /**
     * Create an instance of {@link FlexibleJourneyPatternStructure.FlexibleZones }
     * 
     */
    public FlexibleJourneyPatternStructure.FlexibleZones createFlexibleJourneyPatternStructureFlexibleZones() {
        return new FlexibleJourneyPatternStructure.FlexibleZones();
    }

    /**
     * Create an instance of {@link FlexibleJourneyPatternStructure.FixedStopPoints }
     * 
     */
    public FlexibleJourneyPatternStructure.FixedStopPoints createFlexibleJourneyPatternStructureFixedStopPoints() {
        return new FlexibleJourneyPatternStructure.FixedStopPoints();
    }

    /**
     * Create an instance of {@link DeadRunStructure.PositioningLink }
     * 
     */
    public DeadRunStructure.PositioningLink createDeadRunStructurePositioningLink() {
        return new DeadRunStructure.PositioningLink();
    }

    /**
     * Create an instance of {@link DeadRunStructure.ShortWorking }
     * 
     */
    public DeadRunStructure.ShortWorking createDeadRunStructureShortWorking() {
        return new DeadRunStructure.ShortWorking();
    }

    /**
     * Create an instance of {@link ServiceClassificationStructure.ExcursionOrTour }
     * 
     */
    public ServiceClassificationStructure.ExcursionOrTour createServiceClassificationStructureExcursionOrTour() {
        return new ServiceClassificationStructure.ExcursionOrTour();
    }

    /**
     * Create an instance of {@link ServiceClassificationStructure.OtherService }
     * 
     */
    public ServiceClassificationStructure.OtherService createServiceClassificationStructureOtherService() {
        return new ServiceClassificationStructure.OtherService();
    }

    /**
     * Create an instance of {@link StandardServiceStructure.Vias }
     * 
     */
    public StandardServiceStructure.Vias createStandardServiceStructureVias() {
        return new StandardServiceStructure.Vias();
    }

    /**
     * Create an instance of {@link TrackInstructionsStructure.Feature }
     * 
     */
    public TrackInstructionsStructure.Feature createTrackInstructionsStructureFeature() {
        return new TrackInstructionsStructure.Feature();
    }

    /**
     * Create an instance of {@link FrequentServiceStructure.MinutesPastTheHour }
     * 
     */
    public FrequentServiceStructure.MinutesPastTheHour createFrequentServiceStructureMinutesPastTheHour() {
        return new FrequentServiceStructure.MinutesPastTheHour();
    }

    /**
     * Create an instance of {@link StopRequirementsStructure.NoNewStopsRequired }
     * 
     */
    public StopRequirementsStructure.NoNewStopsRequired createStopRequirementsStructureNoNewStopsRequired() {
        return new StopRequirementsStructure.NoNewStopsRequired();
    }

    /**
     * Create an instance of {@link StopRequirementsStructure.NewStops }
     * 
     */
    public StopRequirementsStructure.NewStops createStopRequirementsStructureNewStops() {
        return new StopRequirementsStructure.NewStops();
    }

    /**
     * Create an instance of {@link VehicleJourneysStructure.FlexibleVehicleJourney }
     * 
     */
    public VehicleJourneysStructure.FlexibleVehicleJourney createVehicleJourneysStructureFlexibleVehicleJourney() {
        return new VehicleJourneysStructure.FlexibleVehicleJourney();
    }

    /**
     * Create an instance of {@link RouteSectionsStructure.RouteSection.RouteLink }
     * 
     */
    public RouteSectionsStructure.RouteSection.RouteLink createRouteSectionsStructureRouteSectionRouteLink() {
        return new RouteSectionsStructure.RouteSection.RouteLink();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationSystemEnumeration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.transxchange.org.uk/", name = "LocationSystem", defaultValue = "Grid")
    public JAXBElement<LocationSystemEnumeration> createLocationSystem(LocationSystemEnumeration value) {
        return new JAXBElement<LocationSystemEnumeration>(_LocationSystem_QNAME, LocationSystemEnumeration.class, null, value);
    }

}
