//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The ShortNoticeRegistration is a replacement for a discontinued service.
 * 
 * <p>Java class for ReplaceDiscontinuedServiceStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReplaceDiscontinuedServiceStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DiscontinuedServiceOperator" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure"/>
 *         &lt;element name="DiscontinuedService" type="{http://www.transxchange.org.uk/}AnnotatedServiceRefStructure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReplaceDiscontinuedServiceStructure", propOrder = {
    "discontinuedServiceOperator",
    "discontinuedService"
})
public class ReplaceDiscontinuedServiceStructure {

    @XmlElement(name = "DiscontinuedServiceOperator", required = true)
    protected NaturalLanguageStringStructure discontinuedServiceOperator;
    @XmlElement(name = "DiscontinuedService", required = true)
    protected AnnotatedServiceRefStructure discontinuedService;

    /**
     * Gets the value of the discontinuedServiceOperator property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getDiscontinuedServiceOperator() {
        return discontinuedServiceOperator;
    }

    /**
     * Sets the value of the discontinuedServiceOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setDiscontinuedServiceOperator(NaturalLanguageStringStructure value) {
        this.discontinuedServiceOperator = value;
    }

    /**
     * Gets the value of the discontinuedService property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotatedServiceRefStructure }
     *     
     */
    public AnnotatedServiceRefStructure getDiscontinuedService() {
        return discontinuedService;
    }

    /**
     * Sets the value of the discontinuedService property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotatedServiceRefStructure }
     *     
     */
    public void setDiscontinuedService(AnnotatedServiceRefStructure value) {
        this.discontinuedService = value;
    }

}
