//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Geospatial representation of route sections for mapping and instructional purposes.
 * 
 * <p>Java class for RouteSectionsStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteSectionsStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RouteSection" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RouteLink" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="From" type="{http://www.transxchange.org.uk/}StopPointWrappedRefStructure"/>
 *                             &lt;element name="To" type="{http://www.transxchange.org.uk/}StopPointWrappedRefStructure"/>
 *                             &lt;element name="Distance" type="{http://www.transxchange.org.uk/}DistanceType" minOccurs="0"/>
 *                             &lt;element name="Direction" type="{http://www.transxchange.org.uk/}LinkDirectionEnumeration" minOccurs="0"/>
 *                             &lt;element name="Track" type="{http://www.transxchange.org.uk/}TrackStructure" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://www.transxchange.org.uk/}ModificationDetailsGroup"/>
 *                           &lt;attribute name="id" type="{http://www.transxchange.org.uk/}IdType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.transxchange.org.uk/}ModificationDetailsGroup"/>
 *                 &lt;attribute name="id" type="{http://www.transxchange.org.uk/}IdType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteSectionsStructure", propOrder = {
    "routeSection"
})
public class RouteSectionsStructure {

    @XmlElement(name = "RouteSection", required = true)
    protected List<RouteSectionsStructure.RouteSection> routeSection;

    /**
     * Gets the value of the routeSection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routeSection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRouteSection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteSectionsStructure.RouteSection }
     * 
     * 
     */
    public List<RouteSectionsStructure.RouteSection> getRouteSection() {
        if (routeSection == null) {
            routeSection = new ArrayList<RouteSectionsStructure.RouteSection>();
        }
        return this.routeSection;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RouteLink" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="From" type="{http://www.transxchange.org.uk/}StopPointWrappedRefStructure"/>
     *                   &lt;element name="To" type="{http://www.transxchange.org.uk/}StopPointWrappedRefStructure"/>
     *                   &lt;element name="Distance" type="{http://www.transxchange.org.uk/}DistanceType" minOccurs="0"/>
     *                   &lt;element name="Direction" type="{http://www.transxchange.org.uk/}LinkDirectionEnumeration" minOccurs="0"/>
     *                   &lt;element name="Track" type="{http://www.transxchange.org.uk/}TrackStructure" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{http://www.transxchange.org.uk/}ModificationDetailsGroup"/>
     *                 &lt;attribute name="id" type="{http://www.transxchange.org.uk/}IdType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.transxchange.org.uk/}ModificationDetailsGroup"/>
     *       &lt;attribute name="id" type="{http://www.transxchange.org.uk/}IdType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "routeLink"
    })
    public static class RouteSection {

        @XmlElement(name = "RouteLink", required = true)
        protected List<RouteSectionsStructure.RouteSection.RouteLink> routeLink;
        @XmlAttribute(name = "id")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String id;
        @XmlAttribute(name = "CreationDateTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar creationDateTime;
        @XmlAttribute(name = "ModificationDateTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar modificationDateTime;
        @XmlAttribute(name = "Modification")
        protected ModificationEnumeration modification;
        @XmlAttribute(name = "RevisionNumber")
        protected BigInteger revisionNumber;
        @XmlAttribute(name = "Status")
        protected StatusEnumeration status;

        /**
         * Gets the value of the routeLink property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the routeLink property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRouteLink().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RouteSectionsStructure.RouteSection.RouteLink }
         * 
         * 
         */
        public List<RouteSectionsStructure.RouteSection.RouteLink> getRouteLink() {
            if (routeLink == null) {
                routeLink = new ArrayList<RouteSectionsStructure.RouteSection.RouteLink>();
            }
            return this.routeLink;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the creationDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreationDateTime() {
            return creationDateTime;
        }

        /**
         * Sets the value of the creationDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreationDateTime(XMLGregorianCalendar value) {
            this.creationDateTime = value;
        }

        /**
         * Gets the value of the modificationDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getModificationDateTime() {
            return modificationDateTime;
        }

        /**
         * Sets the value of the modificationDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setModificationDateTime(XMLGregorianCalendar value) {
            this.modificationDateTime = value;
        }

        /**
         * Gets the value of the modification property.
         * 
         * @return
         *     possible object is
         *     {@link ModificationEnumeration }
         *     
         */
        public ModificationEnumeration getModification() {
            if (modification == null) {
                return ModificationEnumeration.NEW;
            } else {
                return modification;
            }
        }

        /**
         * Sets the value of the modification property.
         * 
         * @param value
         *     allowed object is
         *     {@link ModificationEnumeration }
         *     
         */
        public void setModification(ModificationEnumeration value) {
            this.modification = value;
        }

        /**
         * Gets the value of the revisionNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRevisionNumber() {
            return revisionNumber;
        }

        /**
         * Sets the value of the revisionNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRevisionNumber(BigInteger value) {
            this.revisionNumber = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link StatusEnumeration }
         *     
         */
        public StatusEnumeration getStatus() {
            if (status == null) {
                return StatusEnumeration.ACTIVE;
            } else {
                return status;
            }
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusEnumeration }
         *     
         */
        public void setStatus(StatusEnumeration value) {
            this.status = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="From" type="{http://www.transxchange.org.uk/}StopPointWrappedRefStructure"/>
         *         &lt;element name="To" type="{http://www.transxchange.org.uk/}StopPointWrappedRefStructure"/>
         *         &lt;element name="Distance" type="{http://www.transxchange.org.uk/}DistanceType" minOccurs="0"/>
         *         &lt;element name="Direction" type="{http://www.transxchange.org.uk/}LinkDirectionEnumeration" minOccurs="0"/>
         *         &lt;element name="Track" type="{http://www.transxchange.org.uk/}TrackStructure" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://www.transxchange.org.uk/}ModificationDetailsGroup"/>
         *       &lt;attribute name="id" type="{http://www.transxchange.org.uk/}IdType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "from",
            "to",
            "distance",
            "direction",
            "track"
        })
        public static class RouteLink {

            @XmlElement(name = "From", required = true)
            protected StopPointWrappedRefStructure from;
            @XmlElement(name = "To", required = true)
            protected StopPointWrappedRefStructure to;
            @XmlElement(name = "Distance")
            protected BigInteger distance;
            @XmlElement(name = "Direction")
            protected LinkDirectionEnumeration direction;
            @XmlElement(name = "Track")
            protected List<TrackStructure> track;
            @XmlAttribute(name = "id")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String id;
            @XmlAttribute(name = "CreationDateTime")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar creationDateTime;
            @XmlAttribute(name = "ModificationDateTime")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar modificationDateTime;
            @XmlAttribute(name = "Modification")
            protected ModificationEnumeration modification;
            @XmlAttribute(name = "RevisionNumber")
            protected BigInteger revisionNumber;
            @XmlAttribute(name = "Status")
            protected StatusEnumeration status;

            /**
             * Gets the value of the from property.
             * 
             * @return
             *     possible object is
             *     {@link StopPointWrappedRefStructure }
             *     
             */
            public StopPointWrappedRefStructure getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             * 
             * @param value
             *     allowed object is
             *     {@link StopPointWrappedRefStructure }
             *     
             */
            public void setFrom(StopPointWrappedRefStructure value) {
                this.from = value;
            }

            /**
             * Gets the value of the to property.
             * 
             * @return
             *     possible object is
             *     {@link StopPointWrappedRefStructure }
             *     
             */
            public StopPointWrappedRefStructure getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             * 
             * @param value
             *     allowed object is
             *     {@link StopPointWrappedRefStructure }
             *     
             */
            public void setTo(StopPointWrappedRefStructure value) {
                this.to = value;
            }

            /**
             * Gets the value of the distance property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDistance() {
                return distance;
            }

            /**
             * Sets the value of the distance property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDistance(BigInteger value) {
                this.distance = value;
            }

            /**
             * Gets the value of the direction property.
             * 
             * @return
             *     possible object is
             *     {@link LinkDirectionEnumeration }
             *     
             */
            public LinkDirectionEnumeration getDirection() {
                return direction;
            }

            /**
             * Sets the value of the direction property.
             * 
             * @param value
             *     allowed object is
             *     {@link LinkDirectionEnumeration }
             *     
             */
            public void setDirection(LinkDirectionEnumeration value) {
                this.direction = value;
            }

            /**
             * Gets the value of the track property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the track property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTrack().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TrackStructure }
             * 
             * 
             */
            public List<TrackStructure> getTrack() {
                if (track == null) {
                    track = new ArrayList<TrackStructure>();
                }
                return this.track;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the creationDateTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCreationDateTime() {
                return creationDateTime;
            }

            /**
             * Sets the value of the creationDateTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCreationDateTime(XMLGregorianCalendar value) {
                this.creationDateTime = value;
            }

            /**
             * Gets the value of the modificationDateTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getModificationDateTime() {
                return modificationDateTime;
            }

            /**
             * Sets the value of the modificationDateTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setModificationDateTime(XMLGregorianCalendar value) {
                this.modificationDateTime = value;
            }

            /**
             * Gets the value of the modification property.
             * 
             * @return
             *     possible object is
             *     {@link ModificationEnumeration }
             *     
             */
            public ModificationEnumeration getModification() {
                if (modification == null) {
                    return ModificationEnumeration.NEW;
                } else {
                    return modification;
                }
            }

            /**
             * Sets the value of the modification property.
             * 
             * @param value
             *     allowed object is
             *     {@link ModificationEnumeration }
             *     
             */
            public void setModification(ModificationEnumeration value) {
                this.modification = value;
            }

            /**
             * Gets the value of the revisionNumber property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRevisionNumber() {
                return revisionNumber;
            }

            /**
             * Sets the value of the revisionNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRevisionNumber(BigInteger value) {
                this.revisionNumber = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link StatusEnumeration }
             *     
             */
            public StatusEnumeration getStatus() {
                if (status == null) {
                    return StatusEnumeration.ACTIVE;
                } else {
                    return status;
                }
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link StatusEnumeration }
             *     
             */
            public void setStatus(StatusEnumeration value) {
                this.status = value;
            }

        }

    }

}
