//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Registration is made within less than the statutory period of notice.
 * 
 * <p>Java class for ShortNoticeRegistrationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShortNoticeRegistrationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.transxchange.org.uk/}ChangeImpactGroup"/>
 *         &lt;group ref="{http://www.transxchange.org.uk/}ChangeJustificationGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShortNoticeRegistrationStructure", propOrder = {
    "publicAvailability",
    "changeImpact",
    "bankHolidayChange",
    "changeToConnectAlteredService",
    "replaceDiscontinuedService",
    "localHolidayChange",
    "specialOccasion",
    "regulationOrderCompliance",
    "changeRequestedByExternalAuthority",
    "exceptionalRequirement",
    "miscellaneousJustification"
})
public class ShortNoticeRegistrationStructure {

    @XmlElement(name = "PublicAvailability", required = true)
    protected PublicAvailabilityStructure publicAvailability;
    @XmlElement(name = "ChangeImpact", required = true)
    protected ChangeImpactStructure changeImpact;
    @XmlElement(name = "BankHolidayChange", defaultValue = "false")
    protected Boolean bankHolidayChange;
    @XmlElement(name = "ChangeToConnectAlteredService")
    protected ChangeToConnectAlteredServiceStructure changeToConnectAlteredService;
    @XmlElement(name = "ReplaceDiscontinuedService")
    protected ReplaceDiscontinuedServiceStructure replaceDiscontinuedService;
    @XmlElement(name = "LocalHolidayChange")
    protected LocalHolidayChangeStructure localHolidayChange;
    @XmlElement(name = "SpecialOccasion")
    protected SpecialOccasionStructure specialOccasion;
    @XmlElement(name = "RegulationOrderCompliance")
    protected RegulationOrderComplianceStructure regulationOrderCompliance;
    @XmlElement(name = "ChangeRequestedByExternalAuthority")
    protected ChangeRequestedByExternalAuthorityStructure changeRequestedByExternalAuthority;
    @XmlElement(name = "ExceptionalRequirement")
    protected ExceptionalRequirementStructure exceptionalRequirement;
    @XmlElement(name = "MiscellaneousJustification")
    protected NaturalLanguageStringStructure miscellaneousJustification;

    /**
     * Gets the value of the publicAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link PublicAvailabilityStructure }
     *     
     */
    public PublicAvailabilityStructure getPublicAvailability() {
        return publicAvailability;
    }

    /**
     * Sets the value of the publicAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicAvailabilityStructure }
     *     
     */
    public void setPublicAvailability(PublicAvailabilityStructure value) {
        this.publicAvailability = value;
    }

    /**
     * Gets the value of the changeImpact property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeImpactStructure }
     *     
     */
    public ChangeImpactStructure getChangeImpact() {
        return changeImpact;
    }

    /**
     * Sets the value of the changeImpact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeImpactStructure }
     *     
     */
    public void setChangeImpact(ChangeImpactStructure value) {
        this.changeImpact = value;
    }

    /**
     * Gets the value of the bankHolidayChange property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBankHolidayChange() {
        return bankHolidayChange;
    }

    /**
     * Sets the value of the bankHolidayChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBankHolidayChange(Boolean value) {
        this.bankHolidayChange = value;
    }

    /**
     * Gets the value of the changeToConnectAlteredService property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeToConnectAlteredServiceStructure }
     *     
     */
    public ChangeToConnectAlteredServiceStructure getChangeToConnectAlteredService() {
        return changeToConnectAlteredService;
    }

    /**
     * Sets the value of the changeToConnectAlteredService property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeToConnectAlteredServiceStructure }
     *     
     */
    public void setChangeToConnectAlteredService(ChangeToConnectAlteredServiceStructure value) {
        this.changeToConnectAlteredService = value;
    }

    /**
     * Gets the value of the replaceDiscontinuedService property.
     * 
     * @return
     *     possible object is
     *     {@link ReplaceDiscontinuedServiceStructure }
     *     
     */
    public ReplaceDiscontinuedServiceStructure getReplaceDiscontinuedService() {
        return replaceDiscontinuedService;
    }

    /**
     * Sets the value of the replaceDiscontinuedService property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplaceDiscontinuedServiceStructure }
     *     
     */
    public void setReplaceDiscontinuedService(ReplaceDiscontinuedServiceStructure value) {
        this.replaceDiscontinuedService = value;
    }

    /**
     * Gets the value of the localHolidayChange property.
     * 
     * @return
     *     possible object is
     *     {@link LocalHolidayChangeStructure }
     *     
     */
    public LocalHolidayChangeStructure getLocalHolidayChange() {
        return localHolidayChange;
    }

    /**
     * Sets the value of the localHolidayChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalHolidayChangeStructure }
     *     
     */
    public void setLocalHolidayChange(LocalHolidayChangeStructure value) {
        this.localHolidayChange = value;
    }

    /**
     * Gets the value of the specialOccasion property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialOccasionStructure }
     *     
     */
    public SpecialOccasionStructure getSpecialOccasion() {
        return specialOccasion;
    }

    /**
     * Sets the value of the specialOccasion property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialOccasionStructure }
     *     
     */
    public void setSpecialOccasion(SpecialOccasionStructure value) {
        this.specialOccasion = value;
    }

    /**
     * Gets the value of the regulationOrderCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link RegulationOrderComplianceStructure }
     *     
     */
    public RegulationOrderComplianceStructure getRegulationOrderCompliance() {
        return regulationOrderCompliance;
    }

    /**
     * Sets the value of the regulationOrderCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegulationOrderComplianceStructure }
     *     
     */
    public void setRegulationOrderCompliance(RegulationOrderComplianceStructure value) {
        this.regulationOrderCompliance = value;
    }

    /**
     * Gets the value of the changeRequestedByExternalAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeRequestedByExternalAuthorityStructure }
     *     
     */
    public ChangeRequestedByExternalAuthorityStructure getChangeRequestedByExternalAuthority() {
        return changeRequestedByExternalAuthority;
    }

    /**
     * Sets the value of the changeRequestedByExternalAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeRequestedByExternalAuthorityStructure }
     *     
     */
    public void setChangeRequestedByExternalAuthority(ChangeRequestedByExternalAuthorityStructure value) {
        this.changeRequestedByExternalAuthority = value;
    }

    /**
     * Gets the value of the exceptionalRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionalRequirementStructure }
     *     
     */
    public ExceptionalRequirementStructure getExceptionalRequirement() {
        return exceptionalRequirement;
    }

    /**
     * Sets the value of the exceptionalRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionalRequirementStructure }
     *     
     */
    public void setExceptionalRequirement(ExceptionalRequirementStructure value) {
        this.exceptionalRequirement = value;
    }

    /**
     * Gets the value of the miscellaneousJustification property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getMiscellaneousJustification() {
        return miscellaneousJustification;
    }

    /**
     * Sets the value of the miscellaneousJustification property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setMiscellaneousJustification(NaturalLanguageStringStructure value) {
        this.miscellaneousJustification = value;
    }

}
