//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Classification of the operation or non-operation of the service or journey in respect of special days. Note that the days specified override all other OperatingProfile Days and BankHoliday definitions for the service or journey.
 * 
 * <p>Java class for SpecialDaysOperationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialDaysOperationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DaysOfOperation" type="{http://www.transxchange.org.uk/}AnnotatedClosedDateRangeCollectionStructure" minOccurs="0"/>
 *         &lt;element name="DaysOfNonOperation" type="{http://www.transxchange.org.uk/}AnnotatedClosedDateRangeCollectionStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialDaysOperationStructure", propOrder = {
    "daysOfOperation",
    "daysOfNonOperation"
})
public class SpecialDaysOperationStructure {

    @XmlElement(name = "DaysOfOperation")
    protected AnnotatedClosedDateRangeCollectionStructure daysOfOperation;
    @XmlElement(name = "DaysOfNonOperation")
    protected AnnotatedClosedDateRangeCollectionStructure daysOfNonOperation;

    /**
     * Gets the value of the daysOfOperation property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotatedClosedDateRangeCollectionStructure }
     *     
     */
    public AnnotatedClosedDateRangeCollectionStructure getDaysOfOperation() {
        return daysOfOperation;
    }

    /**
     * Sets the value of the daysOfOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotatedClosedDateRangeCollectionStructure }
     *     
     */
    public void setDaysOfOperation(AnnotatedClosedDateRangeCollectionStructure value) {
        this.daysOfOperation = value;
    }

    /**
     * Gets the value of the daysOfNonOperation property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotatedClosedDateRangeCollectionStructure }
     *     
     */
    public AnnotatedClosedDateRangeCollectionStructure getDaysOfNonOperation() {
        return daysOfNonOperation;
    }

    /**
     * Sets the value of the daysOfNonOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotatedClosedDateRangeCollectionStructure }
     *     
     */
    public void setDaysOfNonOperation(AnnotatedClosedDateRangeCollectionStructure value) {
        this.daysOfNonOperation = value;
    }

}
