//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * A timed link comprising one step of a vehicle journey between two stops. Can be projected on to a corresponding vehicleJourneyTimingLink.
 * 
 * <p>Java class for VehicleJourneyTimingLinkStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleJourneyTimingLinkStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.transxchange.org.uk/}AbstractTimingLinkStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.transxchange.org.uk/}VehicleJourneyTimingLinkGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleJourneyTimingLinkStructure", propOrder = {
    "journeyPatternTimingLinkRef",
    "runTime",
    "from",
    "to"
})
public class VehicleJourneyTimingLinkStructure
    extends AbstractTimingLinkStructure
{

    @XmlElement(name = "JourneyPatternTimingLinkRef", required = true)
    protected TimingLinkRefStructure journeyPatternTimingLinkRef;
    @XmlElement(name = "RunTime")
    protected Duration runTime;
    @XmlElement(name = "From")
    protected VehicleJourneyStopUsageStructure from;
    @XmlElement(name = "To")
    protected VehicleJourneyStopUsageStructure to;

    /**
     * Gets the value of the journeyPatternTimingLinkRef property.
     * 
     * @return
     *     possible object is
     *     {@link TimingLinkRefStructure }
     *     
     */
    public TimingLinkRefStructure getJourneyPatternTimingLinkRef() {
        return journeyPatternTimingLinkRef;
    }

    /**
     * Sets the value of the journeyPatternTimingLinkRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimingLinkRefStructure }
     *     
     */
    public void setJourneyPatternTimingLinkRef(TimingLinkRefStructure value) {
        this.journeyPatternTimingLinkRef = value;
    }

    /**
     * Gets the value of the runTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getRunTime() {
        return runTime;
    }

    /**
     * Sets the value of the runTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setRunTime(Duration value) {
        this.runTime = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleJourneyStopUsageStructure }
     *     
     */
    public VehicleJourneyStopUsageStructure getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleJourneyStopUsageStructure }
     *     
     */
    public void setFrom(VehicleJourneyStopUsageStructure value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleJourneyStopUsageStructure }
     *     
     */
    public VehicleJourneyStopUsageStructure getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleJourneyStopUsageStructure }
     *     
     */
    public void setTo(VehicleJourneyStopUsageStructure value) {
        this.to = value;
    }

}
