//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Veheicle  (TAN) registration number. The registration number is broken down into the three discrete constituent semantic elements it encodes, allowing for better referential integrity. The elements can be concatenated to produce the full number. For example, given the TanCode "PB", the LicenceNumber "0000815", and the RegistrationNumber "123", the full TAN registration number would be "PB0000815/123".
 * 
 * <p>Java class for VosaRegistrationNumberStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VosaRegistrationNumberStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TanCode" type="{http://www.transxchange.org.uk/}TanPrefixEnumeration"/>
 *         &lt;element name="LicenceNumber" type="{http://www.transxchange.org.uk/}OperatorPartialLicenceNumberType"/>
 *         &lt;element name="RegistrationNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VosaRegistrationNumberStructure", propOrder = {
    "tanCode",
    "licenceNumber",
    "registrationNumber"
})
public class VosaRegistrationNumberStructure {

    @XmlElement(name = "TanCode", required = true)
    protected TanPrefixEnumeration tanCode;
    @XmlElement(name = "LicenceNumber", required = true)
    protected String licenceNumber;
    @XmlElement(name = "RegistrationNumber", required = true)
    protected String registrationNumber;

    /**
     * Gets the value of the tanCode property.
     * 
     * @return
     *     possible object is
     *     {@link TanPrefixEnumeration }
     *     
     */
    public TanPrefixEnumeration getTanCode() {
        return tanCode;
    }

    /**
     * Sets the value of the tanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TanPrefixEnumeration }
     *     
     */
    public void setTanCode(TanPrefixEnumeration value) {
        this.tanCode = value;
    }

    /**
     * Gets the value of the licenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenceNumber() {
        return licenceNumber;
    }

    /**
     * Sets the value of the licenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenceNumber(String value) {
        this.licenceNumber = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

}
