//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;


/**
 * Stop usage details for each end of a TimingLink.
 * 
 * <p>Java class for AbstractTimingLinkStopUsageStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractTimingLinkStopUsageStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.transxchange.org.uk/}JourneyStopUsageGroup"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.transxchange.org.uk/}IdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractTimingLinkStopUsageStructure", propOrder = {
    "waitTime",
    "activity",
    "dynamicDestinationDisplay",
    "variableStopAllocations"
})
@XmlSeeAlso({
    VehicleJourneyStopUsageStructure.class,
    JourneyPatternStopUsageStructure.class
})
public class AbstractTimingLinkStopUsageStructure {

    @XmlElement(name = "WaitTime")
    protected Duration waitTime;
    @XmlElement(name = "Activity", defaultValue = "pickUpAndSetDown")
    protected VehicleAtStopActivityEnumeration activity;
    @XmlElement(name = "DynamicDestinationDisplay")
    protected NaturalLanguageStringStructure dynamicDestinationDisplay;
    @XmlElement(name = "VariableStopAllocations")
    protected VariableStopAllocationsStructure variableStopAllocations;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;

    /**
     * Gets the value of the waitTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getWaitTime() {
        return waitTime;
    }

    /**
     * Sets the value of the waitTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setWaitTime(Duration value) {
        this.waitTime = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleAtStopActivityEnumeration }
     *     
     */
    public VehicleAtStopActivityEnumeration getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleAtStopActivityEnumeration }
     *     
     */
    public void setActivity(VehicleAtStopActivityEnumeration value) {
        this.activity = value;
    }

    /**
     * Gets the value of the dynamicDestinationDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getDynamicDestinationDisplay() {
        return dynamicDestinationDisplay;
    }

    /**
     * Sets the value of the dynamicDestinationDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setDynamicDestinationDisplay(NaturalLanguageStringStructure value) {
        this.dynamicDestinationDisplay = value;
    }

    /**
     * Gets the value of the variableStopAllocations property.
     * 
     * @return
     *     possible object is
     *     {@link VariableStopAllocationsStructure }
     *     
     */
    public VariableStopAllocationsStructure getVariableStopAllocations() {
        return variableStopAllocations;
    }

    /**
     * Sets the value of the variableStopAllocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableStopAllocationsStructure }
     *     
     */
    public void setVariableStopAllocations(VariableStopAllocationsStructure value) {
        this.variableStopAllocations = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
