//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Abstract TimingLink definition.
 * 
 * <p>Java class for AbstractTimingLinkStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractTimingLinkStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.transxchange.org.uk/}CommonTimingLinkGroup"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.transxchange.org.uk/}IdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractTimingLinkStructure", propOrder = {
    "hailAndRide",
    "express",
    "stoppingArrangements",
    "dutyCrewCode"
})
@XmlSeeAlso({
    JourneyPatternTimingLinkStructure.class,
    VehicleJourneyTimingLinkStructure.class
})
public class AbstractTimingLinkStructure {

    @XmlElement(name = "HailAndRide", defaultValue = "0")
    protected Boolean hailAndRide;
    @XmlElement(name = "Express", defaultValue = "false")
    protected Boolean express;
    @XmlElement(name = "StoppingArrangements")
    protected NaturalLanguageStringStructure stoppingArrangements;
    @XmlElement(name = "DutyCrewCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dutyCrewCode;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;

    /**
     * Gets the value of the hailAndRide property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHailAndRide() {
        return hailAndRide;
    }

    /**
     * Sets the value of the hailAndRide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHailAndRide(Boolean value) {
        this.hailAndRide = value;
    }

    /**
     * Gets the value of the express property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExpress() {
        return express;
    }

    /**
     * Sets the value of the express property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExpress(Boolean value) {
        this.express = value;
    }

    /**
     * Gets the value of the stoppingArrangements property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getStoppingArrangements() {
        return stoppingArrangements;
    }

    /**
     * Sets the value of the stoppingArrangements property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setStoppingArrangements(NaturalLanguageStringStructure value) {
        this.stoppingArrangements = value;
    }

    /**
     * Gets the value of the dutyCrewCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDutyCrewCode() {
        return dutyCrewCode;
    }

    /**
     * Sets the value of the dutyCrewCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDutyCrewCode(String value) {
        this.dutyCrewCode = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
