//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A flexible journey pattern describes the stops and zones served by a flexible service.
 * @id.
 * @CreationDateTime,
 * @ModificationDateTime,
 * @Modification,
 * @RevisionNumber.
 * 
 * <p>Java class for FlexibleJourneyPatternStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlexibleJourneyPatternStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.transxchange.org.uk/}AbstractJourneyPatternStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.transxchange.org.uk/}FlexibleJourneyPatternGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlexibleJourneyPatternStructure", propOrder = {
    "flexibleZones",
    "fixedStopPoints",
    "bookingArrangements"
})
public class FlexibleJourneyPatternStructure
    extends AbstractJourneyPatternStructure
{

    @XmlElement(name = "FlexibleZones")
    protected FlexibleJourneyPatternStructure.FlexibleZones flexibleZones;
    @XmlElement(name = "FixedStopPoints")
    protected FlexibleJourneyPatternStructure.FixedStopPoints fixedStopPoints;
    @XmlElement(name = "BookingArrangements")
    protected BookingArrangementStructure bookingArrangements;

    /**
     * Gets the value of the flexibleZones property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleJourneyPatternStructure.FlexibleZones }
     *     
     */
    public FlexibleJourneyPatternStructure.FlexibleZones getFlexibleZones() {
        return flexibleZones;
    }

    /**
     * Sets the value of the flexibleZones property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleJourneyPatternStructure.FlexibleZones }
     *     
     */
    public void setFlexibleZones(FlexibleJourneyPatternStructure.FlexibleZones value) {
        this.flexibleZones = value;
    }

    /**
     * Gets the value of the fixedStopPoints property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleJourneyPatternStructure.FixedStopPoints }
     *     
     */
    public FlexibleJourneyPatternStructure.FixedStopPoints getFixedStopPoints() {
        return fixedStopPoints;
    }

    /**
     * Sets the value of the fixedStopPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleJourneyPatternStructure.FixedStopPoints }
     *     
     */
    public void setFixedStopPoints(FlexibleJourneyPatternStructure.FixedStopPoints value) {
        this.fixedStopPoints = value;
    }

    /**
     * Gets the value of the bookingArrangements property.
     * 
     * @return
     *     possible object is
     *     {@link BookingArrangementStructure }
     *     
     */
    public BookingArrangementStructure getBookingArrangements() {
        return bookingArrangements;
    }

    /**
     * Sets the value of the bookingArrangements property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingArrangementStructure }
     *     
     */
    public void setBookingArrangements(BookingArrangementStructure value) {
        this.bookingArrangements = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FixedStopUsage" type="{http://www.transxchange.org.uk/}JourneyPatternStopUsageStructure" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fixedStopUsage"
    })
    public static class FixedStopPoints {

        @XmlElement(name = "FixedStopUsage", required = true)
        protected List<JourneyPatternStopUsageStructure> fixedStopUsage;

        /**
         * Gets the value of the fixedStopUsage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fixedStopUsage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFixedStopUsage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JourneyPatternStopUsageStructure }
         * 
         * 
         */
        public List<JourneyPatternStopUsageStructure> getFixedStopUsage() {
            if (fixedStopUsage == null) {
                fixedStopUsage = new ArrayList<JourneyPatternStopUsageStructure>();
            }
            return this.fixedStopUsage;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FlexibleStopUsage" type="{http://www.transxchange.org.uk/}FlexibleJourneyPatternStopUsageStructure" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flexibleStopUsage"
    })
    public static class FlexibleZones {

        @XmlElement(name = "FlexibleStopUsage", required = true)
        protected List<FlexibleJourneyPatternStopUsageStructure> flexibleStopUsage;

        /**
         * Gets the value of the flexibleStopUsage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flexibleStopUsage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlexibleStopUsage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FlexibleJourneyPatternStopUsageStructure }
         * 
         * 
         */
        public List<FlexibleJourneyPatternStopUsageStructure> getFlexibleStopUsage() {
            if (flexibleStopUsage == null) {
                flexibleStopUsage = new ArrayList<FlexibleJourneyPatternStopUsageStructure>();
            }
            return this.flexibleStopUsage;
        }

    }

}
