//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Describes the characteristics of a Frequent Service, that is, a service where stops are served at a frequency of 10 minutes or less for the whole or part of the day.
 * 
 * <p>Java class for FrequentServiceStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FrequentServiceStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;choice>
 *           &lt;element name="Interval" type="{http://www.transxchange.org.uk/}FrequencyStructure"/>
 *           &lt;element name="MinutesPastTheHour">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Minutes" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" maxOccurs="60"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="FrequentService" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FrequentServiceStructure", propOrder = {
    "endTime",
    "interval",
    "minutesPastTheHour",
    "frequentService"
})
public class FrequentServiceStructure {

    @XmlElement(name = "EndTime", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar endTime;
    @XmlElement(name = "Interval")
    protected FrequencyStructure interval;
    @XmlElement(name = "MinutesPastTheHour")
    protected FrequentServiceStructure.MinutesPastTheHour minutesPastTheHour;
    @XmlElement(name = "FrequentService", defaultValue = "false")
    protected Boolean frequentService;

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyStructure }
     *     
     */
    public FrequencyStructure getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyStructure }
     *     
     */
    public void setInterval(FrequencyStructure value) {
        this.interval = value;
    }

    /**
     * Gets the value of the minutesPastTheHour property.
     * 
     * @return
     *     possible object is
     *     {@link FrequentServiceStructure.MinutesPastTheHour }
     *     
     */
    public FrequentServiceStructure.MinutesPastTheHour getMinutesPastTheHour() {
        return minutesPastTheHour;
    }

    /**
     * Sets the value of the minutesPastTheHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequentServiceStructure.MinutesPastTheHour }
     *     
     */
    public void setMinutesPastTheHour(FrequentServiceStructure.MinutesPastTheHour value) {
        this.minutesPastTheHour = value;
    }

    /**
     * Gets the value of the frequentService property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFrequentService() {
        return frequentService;
    }

    /**
     * Sets the value of the frequentService property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFrequentService(Boolean value) {
        this.frequentService = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Minutes" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" maxOccurs="60"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "minutes"
    })
    public static class MinutesPastTheHour {

        @XmlElement(name = "Minutes", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected List<BigInteger> minutes;

        /**
         * Gets the value of the minutes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the minutes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMinutes().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BigInteger }
         * 
         * 
         */
        public List<BigInteger> getMinutes() {
            if (minutes == null) {
                minutes = new ArrayList<BigInteger>();
            }
            return this.minutes;
        }

    }

}
