//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * @LocationRef
 * 
 * A node in the interchange model. Each node has a type indicating its primary function (for example, a rail platform would have a type of "rail")
 * 
 * <p>Java class for InterchangeNodeStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterchangeNodeStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="InterchangeNodeType" type="{http://www.transxchange.org.uk/}InterchangeNodeTypeEnumeration"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StopPointRef" type="{http://www.transxchange.org.uk/}StopPointRefStructure" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="LocationRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterchangeNodeStructure", propOrder = {

})
public class InterchangeNodeStructure {

    @XmlElement(name = "InterchangeNodeType", required = true)
    protected InterchangeNodeTypeEnumeration interchangeNodeType;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "StopPointRef")
    protected StopPointRefStructure stopPointRef;
    @XmlAttribute(name = "LocationRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object locationRef;

    /**
     * Gets the value of the interchangeNodeType property.
     * 
     * @return
     *     possible object is
     *     {@link InterchangeNodeTypeEnumeration }
     *     
     */
    public InterchangeNodeTypeEnumeration getInterchangeNodeType() {
        return interchangeNodeType;
    }

    /**
     * Sets the value of the interchangeNodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterchangeNodeTypeEnumeration }
     *     
     */
    public void setInterchangeNodeType(InterchangeNodeTypeEnumeration value) {
        this.interchangeNodeType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the stopPointRef property.
     * 
     * @return
     *     possible object is
     *     {@link StopPointRefStructure }
     *     
     */
    public StopPointRefStructure getStopPointRef() {
        return stopPointRef;
    }

    /**
     * Sets the value of the stopPointRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopPointRefStructure }
     *     
     */
    public void setStopPointRef(StopPointRefStructure value) {
        this.stopPointRef = value;
    }

    /**
     * Gets the value of the locationRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLocationRef() {
        return locationRef;
    }

    /**
     * Sets the value of the locationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLocationRef(Object value) {
        this.locationRef = value;
    }

}
