//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A JourneyPattern is an ordered collection of JourneyPatternTimingLink elements and represents the pattern of working for vehicles of the service. Note that the order of JourneyPatternTimingLink elements in the JourneyPattern element must follow the order in which they appear in the Route. It should also be noted that VehicleJourneys following a JourneyPattern must run over the exact route, but need not stop at all Stops identified within the JourneyPattern, thus the JourneyPattern provides the 'set' of Stops of which all or some may be served by the related VehicleJourneys.
 * @id.
 * @CreationDateTime,
 * @ModificationDateTime,
 * @Modification,
 * @RevisionNumber.
 * 
 * <p>Java class for JourneyPatternStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JourneyPatternStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.transxchange.org.uk/}AbstractJourneyPatternStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.transxchange.org.uk/}StandardJourneyPatternGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JourneyPatternStructure", propOrder = {
    "routeRef",
    "journeyPatternSectionRefs"
})
public class JourneyPatternStructure
    extends AbstractJourneyPatternStructure
{

    @XmlElement(name = "RouteRef")
    protected RouteRefStructure routeRef;
    @XmlElement(name = "JourneyPatternSectionRefs", required = true)
    protected List<JourneyPatternSectionRefStructure> journeyPatternSectionRefs;

    /**
     * Gets the value of the routeRef property.
     * 
     * @return
     *     possible object is
     *     {@link RouteRefStructure }
     *     
     */
    public RouteRefStructure getRouteRef() {
        return routeRef;
    }

    /**
     * Sets the value of the routeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteRefStructure }
     *     
     */
    public void setRouteRef(RouteRefStructure value) {
        this.routeRef = value;
    }

    /**
     * Gets the value of the journeyPatternSectionRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journeyPatternSectionRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJourneyPatternSectionRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JourneyPatternSectionRefStructure }
     * 
     * 
     */
    public List<JourneyPatternSectionRefStructure> getJourneyPatternSectionRefs() {
        if (journeyPatternSectionRefs == null) {
            journeyPatternSectionRefs = new ArrayList<JourneyPatternSectionRefStructure>();
        }
        return this.journeyPatternSectionRefs;
    }

}
