//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of one or more operators.
 * 
 * <p>Java class for OperatorsStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperatorsStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="Operator" type="{http://www.transxchange.org.uk/}OperatorStructure" minOccurs="0"/>
 *         &lt;element name="LicensedOperator" type="{http://www.transxchange.org.uk/}LicensedOperatorStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperatorsStructure", propOrder = {
    "operatorAndLicensedOperator"
})
public class OperatorsStructure {

    @XmlElements({
        @XmlElement(name = "Operator"),
        @XmlElement(name = "LicensedOperator", type = LicensedOperatorStructure.class)
    })
    protected List<OperatorStructure> operatorAndLicensedOperator;

    /**
     * Gets the value of the operatorAndLicensedOperator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operatorAndLicensedOperator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperatorAndLicensedOperator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperatorStructure }
     * {@link LicensedOperatorStructure }
     * 
     * 
     */
    public List<OperatorStructure> getOperatorAndLicensedOperator() {
        if (operatorAndLicensedOperator == null) {
            operatorAndLicensedOperator = new ArrayList<OperatorStructure>();
        }
        return this.operatorAndLicensedOperator;
    }

}
