//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import uk.gov.govtalk.people.addressandpersonaldetails.UKPostalAddressStructure;


/**
 * Collection of addresses for the operator (as a minimum this must include the correspondence address).
 * 
 * <p>Java class for OperatorAddressesStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperatorAddressesStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CorrespondenceAddress" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}UKPostalAddressStructure"/>
 *         &lt;element name="MiscellaneousAddress" type="{http://www.govtalk.gov.uk/people/AddressAndPersonalDetails}UKPostalAddressStructure" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperatorAddressesStructure", propOrder = {
    "correspondenceAddress",
    "miscellaneousAddress"
})
public class OperatorAddressesStructure {

    @XmlElement(name = "CorrespondenceAddress", required = true)
    protected UKPostalAddressStructure correspondenceAddress;
    @XmlElement(name = "MiscellaneousAddress")
    protected List<UKPostalAddressStructure> miscellaneousAddress;

    /**
     * Gets the value of the correspondenceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link UKPostalAddressStructure }
     *     
     */
    public UKPostalAddressStructure getCorrespondenceAddress() {
        return correspondenceAddress;
    }

    /**
     * Sets the value of the correspondenceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link UKPostalAddressStructure }
     *     
     */
    public void setCorrespondenceAddress(UKPostalAddressStructure value) {
        this.correspondenceAddress = value;
    }

    /**
     * Gets the value of the miscellaneousAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miscellaneousAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMiscellaneousAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UKPostalAddressStructure }
     * 
     * 
     */
    public List<UKPostalAddressStructure> getMiscellaneousAddress() {
        if (miscellaneousAddress == null) {
            miscellaneousAddress = new ArrayList<UKPostalAddressStructure>();
        }
        return this.miscellaneousAddress;
    }

}
