//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Whether the service is to be available to the public. Applies only to short notice registrations.
 * 
 * <p>Java class for PublicAvailabilityStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicAvailabilityStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="AvailableToPublic">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NotAvailableToPublic">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NonAvailabilityDescription" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicAvailabilityStructure", propOrder = {
    "availableToPublic",
    "notAvailableToPublic"
})
public class PublicAvailabilityStructure {

    @XmlElement(name = "AvailableToPublic")
    protected PublicAvailabilityStructure.AvailableToPublic availableToPublic;
    @XmlElement(name = "NotAvailableToPublic")
    protected PublicAvailabilityStructure.NotAvailableToPublic notAvailableToPublic;

    /**
     * Gets the value of the availableToPublic property.
     * 
     * @return
     *     possible object is
     *     {@link PublicAvailabilityStructure.AvailableToPublic }
     *     
     */
    public PublicAvailabilityStructure.AvailableToPublic getAvailableToPublic() {
        return availableToPublic;
    }

    /**
     * Sets the value of the availableToPublic property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicAvailabilityStructure.AvailableToPublic }
     *     
     */
    public void setAvailableToPublic(PublicAvailabilityStructure.AvailableToPublic value) {
        this.availableToPublic = value;
    }

    /**
     * Gets the value of the notAvailableToPublic property.
     * 
     * @return
     *     possible object is
     *     {@link PublicAvailabilityStructure.NotAvailableToPublic }
     *     
     */
    public PublicAvailabilityStructure.NotAvailableToPublic getNotAvailableToPublic() {
        return notAvailableToPublic;
    }

    /**
     * Sets the value of the notAvailableToPublic property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicAvailabilityStructure.NotAvailableToPublic }
     *     
     */
    public void setNotAvailableToPublic(PublicAvailabilityStructure.NotAvailableToPublic value) {
        this.notAvailableToPublic = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AvailableToPublic {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NonAvailabilityDescription" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nonAvailabilityDescription"
    })
    public static class NotAvailableToPublic {

        @XmlElement(name = "NonAvailabilityDescription", required = true)
        protected NaturalLanguageStringStructure nonAvailabilityDescription;

        /**
         * Gets the value of the nonAvailabilityDescription property.
         * 
         * @return
         *     possible object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public NaturalLanguageStringStructure getNonAvailabilityDescription() {
            return nonAvailabilityDescription;
        }

        /**
         * Sets the value of the nonAvailabilityDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public void setNonAvailabilityDescription(NaturalLanguageStringStructure value) {
            this.nonAvailabilityDescription = value;
        }

    }

}
