//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Registration of a service with a regulator for authorisation to provide a service.
 * 
 * <p>Java class for RegistrationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistrationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceRef" type="{http://www.transxchange.org.uk/}ServiceRefStructure"/>
 *         &lt;group ref="{http://www.transxchange.org.uk/}RegistrationSubmissionGroup"/>
 *         &lt;group ref="{http://www.transxchange.org.uk/}RegistrationInfoGroup"/>
 *         &lt;element name="ShortNoticeRegistration" type="{http://www.transxchange.org.uk/}ShortNoticeRegistrationStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.transxchange.org.uk/}ModificationDetailsGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistrationStructure", propOrder = {
    "serviceRef",
    "submissionDate",
    "vosaRegistrationNumber",
    "applicationClassification",
    "variationNumber",
    "submissionAuthor",
    "trafficAreas",
    "circulatedAuthorities",
    "subsidyDetails",
    "contractedService",
    "qualityPartnership",
    "supportingDocuments",
    "shortNoticeRegistration"
})
public class RegistrationStructure {

    @XmlElement(name = "ServiceRef", required = true)
    protected ServiceRefStructure serviceRef;
    @XmlElement(name = "SubmissionDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar submissionDate;
    @XmlElement(name = "VosaRegistrationNumber", required = true)
    protected VosaRegistrationNumberStructure vosaRegistrationNumber;
    @XmlElement(name = "ApplicationClassification", required = true)
    protected RegistrationApplicationEnumeration applicationClassification;
    @XmlElement(name = "VariationNumber", required = true)
    protected BigInteger variationNumber;
    @XmlElement(name = "SubmissionAuthor", required = true)
    protected FullPersonNameStructure submissionAuthor;
    @XmlElement(name = "TrafficAreas", required = true)
    protected TrafficAreasStructure trafficAreas;
    @XmlElement(name = "CirculatedAuthorities", required = true)
    protected CirculatedAuthoritiesStructure circulatedAuthorities;
    @XmlElement(name = "SubsidyDetails", required = true)
    protected SubsidyDetailsStructure subsidyDetails;
    @XmlElement(name = "ContractedService")
    protected RegistrationStructure.ContractedService contractedService;
    @XmlElement(name = "QualityPartnership")
    protected NaturalLanguageStringStructure qualityPartnership;
    @XmlElement(name = "SupportingDocuments")
    protected SupportingDocumentsStructure supportingDocuments;
    @XmlElement(name = "ShortNoticeRegistration")
    protected ShortNoticeRegistrationStructure shortNoticeRegistration;
    @XmlAttribute(name = "CreationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "ModificationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modificationDateTime;
    @XmlAttribute(name = "Modification")
    protected ModificationEnumeration modification;
    @XmlAttribute(name = "RevisionNumber")
    protected BigInteger revisionNumber;
    @XmlAttribute(name = "Status")
    protected StatusEnumeration status;

    /**
     * Gets the value of the serviceRef property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRefStructure }
     *     
     */
    public ServiceRefStructure getServiceRef() {
        return serviceRef;
    }

    /**
     * Sets the value of the serviceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRefStructure }
     *     
     */
    public void setServiceRef(ServiceRefStructure value) {
        this.serviceRef = value;
    }

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionDate() {
        return submissionDate;
    }

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionDate(XMLGregorianCalendar value) {
        this.submissionDate = value;
    }

    /**
     * Gets the value of the vosaRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link VosaRegistrationNumberStructure }
     *     
     */
    public VosaRegistrationNumberStructure getVosaRegistrationNumber() {
        return vosaRegistrationNumber;
    }

    /**
     * Sets the value of the vosaRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link VosaRegistrationNumberStructure }
     *     
     */
    public void setVosaRegistrationNumber(VosaRegistrationNumberStructure value) {
        this.vosaRegistrationNumber = value;
    }

    /**
     * Gets the value of the applicationClassification property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationApplicationEnumeration }
     *     
     */
    public RegistrationApplicationEnumeration getApplicationClassification() {
        return applicationClassification;
    }

    /**
     * Sets the value of the applicationClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationApplicationEnumeration }
     *     
     */
    public void setApplicationClassification(RegistrationApplicationEnumeration value) {
        this.applicationClassification = value;
    }

    /**
     * Gets the value of the variationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVariationNumber() {
        return variationNumber;
    }

    /**
     * Sets the value of the variationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVariationNumber(BigInteger value) {
        this.variationNumber = value;
    }

    /**
     * Gets the value of the submissionAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link FullPersonNameStructure }
     *     
     */
    public FullPersonNameStructure getSubmissionAuthor() {
        return submissionAuthor;
    }

    /**
     * Sets the value of the submissionAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullPersonNameStructure }
     *     
     */
    public void setSubmissionAuthor(FullPersonNameStructure value) {
        this.submissionAuthor = value;
    }

    /**
     * Gets the value of the trafficAreas property.
     * 
     * @return
     *     possible object is
     *     {@link TrafficAreasStructure }
     *     
     */
    public TrafficAreasStructure getTrafficAreas() {
        return trafficAreas;
    }

    /**
     * Sets the value of the trafficAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrafficAreasStructure }
     *     
     */
    public void setTrafficAreas(TrafficAreasStructure value) {
        this.trafficAreas = value;
    }

    /**
     * Gets the value of the circulatedAuthorities property.
     * 
     * @return
     *     possible object is
     *     {@link CirculatedAuthoritiesStructure }
     *     
     */
    public CirculatedAuthoritiesStructure getCirculatedAuthorities() {
        return circulatedAuthorities;
    }

    /**
     * Sets the value of the circulatedAuthorities property.
     * 
     * @param value
     *     allowed object is
     *     {@link CirculatedAuthoritiesStructure }
     *     
     */
    public void setCirculatedAuthorities(CirculatedAuthoritiesStructure value) {
        this.circulatedAuthorities = value;
    }

    /**
     * Gets the value of the subsidyDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SubsidyDetailsStructure }
     *     
     */
    public SubsidyDetailsStructure getSubsidyDetails() {
        return subsidyDetails;
    }

    /**
     * Sets the value of the subsidyDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubsidyDetailsStructure }
     *     
     */
    public void setSubsidyDetails(SubsidyDetailsStructure value) {
        this.subsidyDetails = value;
    }

    /**
     * Gets the value of the contractedService property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationStructure.ContractedService }
     *     
     */
    public RegistrationStructure.ContractedService getContractedService() {
        return contractedService;
    }

    /**
     * Sets the value of the contractedService property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationStructure.ContractedService }
     *     
     */
    public void setContractedService(RegistrationStructure.ContractedService value) {
        this.contractedService = value;
    }

    /**
     * Gets the value of the qualityPartnership property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getQualityPartnership() {
        return qualityPartnership;
    }

    /**
     * Sets the value of the qualityPartnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setQualityPartnership(NaturalLanguageStringStructure value) {
        this.qualityPartnership = value;
    }

    /**
     * Gets the value of the supportingDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link SupportingDocumentsStructure }
     *     
     */
    public SupportingDocumentsStructure getSupportingDocuments() {
        return supportingDocuments;
    }

    /**
     * Sets the value of the supportingDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportingDocumentsStructure }
     *     
     */
    public void setSupportingDocuments(SupportingDocumentsStructure value) {
        this.supportingDocuments = value;
    }

    /**
     * Gets the value of the shortNoticeRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link ShortNoticeRegistrationStructure }
     *     
     */
    public ShortNoticeRegistrationStructure getShortNoticeRegistration() {
        return shortNoticeRegistration;
    }

    /**
     * Sets the value of the shortNoticeRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortNoticeRegistrationStructure }
     *     
     */
    public void setShortNoticeRegistration(ShortNoticeRegistrationStructure value) {
        this.shortNoticeRegistration = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the modificationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModificationDateTime() {
        return modificationDateTime;
    }

    /**
     * Sets the value of the modificationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModificationDateTime(XMLGregorianCalendar value) {
        this.modificationDateTime = value;
    }

    /**
     * Gets the value of the modification property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationEnumeration }
     *     
     */
    public ModificationEnumeration getModification() {
        if (modification == null) {
            return ModificationEnumeration.NEW;
        } else {
            return modification;
        }
    }

    /**
     * Sets the value of the modification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationEnumeration }
     *     
     */
    public void setModification(ModificationEnumeration value) {
        this.modification = value;
    }

    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevisionNumber(BigInteger value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusEnumeration }
     *     
     */
    public StatusEnumeration getStatus() {
        if (status == null) {
            return StatusEnumeration.ACTIVE;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusEnumeration }
     *     
     */
    public void setStatus(StatusEnumeration value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="NotContracted" type="{http://www.transxchange.org.uk/}EmptyType"/>
     *           &lt;sequence>
     *             &lt;choice>
     *               &lt;element name="WhollyContracted" type="{http://www.transxchange.org.uk/}EmptyType"/>
     *               &lt;element name="PartContracted" type="{http://www.transxchange.org.uk/}EmptyType"/>
     *             &lt;/choice>
     *             &lt;element name="ContractingAuthority" type="{http://www.transxchange.org.uk/}AuthorityRefStructure" maxOccurs="unbounded"/>
     *           &lt;/sequence>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "notContracted",
        "whollyContracted",
        "partContracted",
        "contractingAuthority"
    })
    public static class ContractedService {

        @XmlElement(name = "NotContracted")
        protected String notContracted;
        @XmlElement(name = "WhollyContracted")
        protected String whollyContracted;
        @XmlElement(name = "PartContracted")
        protected String partContracted;
        @XmlElement(name = "ContractingAuthority")
        protected List<AuthorityRefStructure> contractingAuthority;

        /**
         * Gets the value of the notContracted property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotContracted() {
            return notContracted;
        }

        /**
         * Sets the value of the notContracted property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotContracted(String value) {
            this.notContracted = value;
        }

        /**
         * Gets the value of the whollyContracted property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWhollyContracted() {
            return whollyContracted;
        }

        /**
         * Sets the value of the whollyContracted property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWhollyContracted(String value) {
            this.whollyContracted = value;
        }

        /**
         * Gets the value of the partContracted property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartContracted() {
            return partContracted;
        }

        /**
         * Sets the value of the partContracted property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartContracted(String value) {
            this.partContracted = value;
        }

        /**
         * Gets the value of the contractingAuthority property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contractingAuthority property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContractingAuthority().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AuthorityRefStructure }
         * 
         * 
         */
        public List<AuthorityRefStructure> getContractingAuthority() {
            if (contractingAuthority == null) {
                contractingAuthority = new ArrayList<AuthorityRefStructure>();
            }
            return this.contractingAuthority;
        }

    }

}
