//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Whether the service requires any new stops.
 * 
 * <p>Java class for StopRequirementsStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopRequirementsStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="NoNewStopsRequired">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NewStops">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="StopPointRef" type="{http://www.transxchange.org.uk/}StopPointRefStructure"/>
 *                   &lt;element name="Note" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopRequirementsStructure", propOrder = {
    "noNewStopsRequired",
    "newStops"
})
public class StopRequirementsStructure {

    @XmlElement(name = "NoNewStopsRequired")
    protected StopRequirementsStructure.NoNewStopsRequired noNewStopsRequired;
    @XmlElement(name = "NewStops")
    protected StopRequirementsStructure.NewStops newStops;

    /**
     * Gets the value of the noNewStopsRequired property.
     * 
     * @return
     *     possible object is
     *     {@link StopRequirementsStructure.NoNewStopsRequired }
     *     
     */
    public StopRequirementsStructure.NoNewStopsRequired getNoNewStopsRequired() {
        return noNewStopsRequired;
    }

    /**
     * Sets the value of the noNewStopsRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopRequirementsStructure.NoNewStopsRequired }
     *     
     */
    public void setNoNewStopsRequired(StopRequirementsStructure.NoNewStopsRequired value) {
        this.noNewStopsRequired = value;
    }

    /**
     * Gets the value of the newStops property.
     * 
     * @return
     *     possible object is
     *     {@link StopRequirementsStructure.NewStops }
     *     
     */
    public StopRequirementsStructure.NewStops getNewStops() {
        return newStops;
    }

    /**
     * Sets the value of the newStops property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopRequirementsStructure.NewStops }
     *     
     */
    public void setNewStops(StopRequirementsStructure.NewStops value) {
        this.newStops = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="StopPointRef" type="{http://www.transxchange.org.uk/}StopPointRefStructure"/>
     *         &lt;element name="Note" type="{http://www.transxchange.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stopPointRefAndNote"
    })
    public static class NewStops {

        @XmlElements({
            @XmlElement(name = "StopPointRef", required = true, type = StopPointRefStructure.class),
            @XmlElement(name = "Note", required = true, type = NaturalLanguageStringStructure.class)
        })
        protected List<Object> stopPointRefAndNote;

        /**
         * Gets the value of the stopPointRefAndNote property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stopPointRefAndNote property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStopPointRefAndNote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StopPointRefStructure }
         * {@link NaturalLanguageStringStructure }
         * 
         * 
         */
        public List<Object> getStopPointRefAndNote() {
            if (stopPointRefAndNote == null) {
                stopPointRefAndNote = new ArrayList<Object>();
            }
            return this.stopPointRefAndNote;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NoNewStopsRequired {


    }

}
