//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeDemandEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TimeDemandEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="earlyMorning"/>
 *     &lt;enumeration value="peakMorning"/>
 *     &lt;enumeration value="offPeak"/>
 *     &lt;enumeration value="peakAfternoon"/>
 *     &lt;enumeration value="evening"/>
 *     &lt;enumeration value="lateEvening"/>
 *     &lt;enumeration value="saturdayMorning"/>
 *     &lt;enumeration value="saturdayDaytime"/>
 *     &lt;enumeration value="saturdayEvening"/>
 *     &lt;enumeration value="sunday"/>
 *     &lt;enumeration value="bankHoliday"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TimeDemandEnumeration")
@XmlEnum
public enum TimeDemandEnumeration {

    @XmlEnumValue("earlyMorning")
    EARLY_MORNING("earlyMorning"),
    @XmlEnumValue("peakMorning")
    PEAK_MORNING("peakMorning"),
    @XmlEnumValue("offPeak")
    OFF_PEAK("offPeak"),
    @XmlEnumValue("peakAfternoon")
    PEAK_AFTERNOON("peakAfternoon"),
    @XmlEnumValue("evening")
    EVENING("evening"),
    @XmlEnumValue("lateEvening")
    LATE_EVENING("lateEvening"),
    @XmlEnumValue("saturdayMorning")
    SATURDAY_MORNING("saturdayMorning"),
    @XmlEnumValue("saturdayDaytime")
    SATURDAY_DAYTIME("saturdayDaytime"),
    @XmlEnumValue("saturdayEvening")
    SATURDAY_EVENING("saturdayEvening"),
    @XmlEnumValue("sunday")
    SUNDAY("sunday"),
    @XmlEnumValue("bankHoliday")
    BANK_HOLIDAY("bankHoliday");
    private final String value;

    TimeDemandEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimeDemandEnumeration fromValue(String v) {
        for (TimeDemandEnumeration c: TimeDemandEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
