//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Traffic Area.
 * 
 * <p>Java class for TrafficAreaStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrafficAreaStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrafficAreaName" type="{http://www.transxchange.org.uk/}TrafficAreaNameEnumeration"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrafficAreaStructure", propOrder = {
    "trafficAreaName"
})
public class TrafficAreaStructure {

    @XmlElement(name = "TrafficAreaName", required = true)
    protected TrafficAreaNameEnumeration trafficAreaName;

    /**
     * Gets the value of the trafficAreaName property.
     * 
     * @return
     *     possible object is
     *     {@link TrafficAreaNameEnumeration }
     *     
     */
    public TrafficAreaNameEnumeration getTrafficAreaName() {
        return trafficAreaName;
    }

    /**
     * Sets the value of the trafficAreaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrafficAreaNameEnumeration }
     *     
     */
    public void setTrafficAreaName(TrafficAreaNameEnumeration value) {
        this.trafficAreaName = value;
    }

}
