//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of stops or annotated stop refs.
 * 
 * <p>Java class for TransXChangeStopPointsStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransXChangeStopPointsStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StopPoint" type="{http://www.transxchange.org.uk/}StopPointStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AnnotatedStopPointRef" type="{http://www.transxchange.org.uk/}AnnotatedStopPointRefStructure" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransXChangeStopPointsStructure", propOrder = {
    "stopPoint",
    "annotatedStopPointRef"
})
public class TransXChangeStopPointsStructure {

    @XmlElement(name = "StopPoint")
    protected List<StopPointStructure> stopPoint;
    @XmlElement(name = "AnnotatedStopPointRef")
    protected List<AnnotatedStopPointRefStructure> annotatedStopPointRef;

    /**
     * Gets the value of the stopPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StopPointStructure }
     * 
     * 
     */
    public List<StopPointStructure> getStopPoint() {
        if (stopPoint == null) {
            stopPoint = new ArrayList<StopPointStructure>();
        }
        return this.stopPoint;
    }

    /**
     * Gets the value of the annotatedStopPointRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotatedStopPointRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotatedStopPointRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotatedStopPointRefStructure }
     * 
     * 
     */
    public List<AnnotatedStopPointRefStructure> getAnnotatedStopPointRef() {
        if (annotatedStopPointRef == null) {
            annotatedStopPointRef = new ArrayList<AnnotatedStopPointRefStructure>();
        }
        return this.annotatedStopPointRef;
    }

}
