//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServicedOrganisations" type="{http://www.transxchange.org.uk/}ServicedOrganisationsStructure" minOccurs="0"/>
 *         &lt;element name="NptgLocalities" type="{http://www.transxchange.org.uk/}TransXChangeNptgLocalitiesStructure" minOccurs="0"/>
 *         &lt;element name="StopPoints" type="{http://www.transxchange.org.uk/}TransXChangeStopPointsStructure" minOccurs="0"/>
 *         &lt;element name="StopAreas" type="{http://www.transxchange.org.uk/}StopAreasStructure" minOccurs="0"/>
 *         &lt;element name="RouteSections" type="{http://www.transxchange.org.uk/}RouteSectionsStructure" minOccurs="0"/>
 *         &lt;element name="Routes" type="{http://www.transxchange.org.uk/}RoutesStructure" minOccurs="0"/>
 *         &lt;element name="JourneyPatternSections" type="{http://www.transxchange.org.uk/}JourneyPatternSectionsStructure" minOccurs="0"/>
 *         &lt;element name="Operators" type="{http://www.transxchange.org.uk/}OperatorsStructure" minOccurs="0"/>
 *         &lt;element name="Services" type="{http://www.transxchange.org.uk/}ServicesStructure" minOccurs="0"/>
 *         &lt;element name="VehicleJourneys" type="{http://www.transxchange.org.uk/}VehicleJourneysStructure" minOccurs="0"/>
 *         &lt;element name="Registrations" type="{http://www.transxchange.org.uk/}RegistrationsStructure" minOccurs="0"/>
 *         &lt;element name="SupportingDocuments" type="{http://www.transxchange.org.uk/}SupportingDocumentsStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.transxchange.org.uk/}DocumentMetadataGroup"/>
 *       &lt;attGroup ref="{http://www.transxchange.org.uk/}DocumentModificationDetailsGroup"/>
 *       &lt;attribute name="LocationSystem" type="{http://www.transxchange.org.uk/}LocationSystemEnumeration" />
 *       &lt;attribute name="RegistrationDocument" type="{http://www.transxchange.org.uk/}RegistrationDocumentType" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "servicedOrganisations",
    "nptgLocalities",
    "stopPoints",
    "stopAreas",
    "routeSections",
    "routes",
    "journeyPatternSections",
    "operators",
    "services",
    "vehicleJourneys",
    "registrations",
    "supportingDocuments"
})
@XmlRootElement(name = "TransXChange")
public class TransXChange {

    @XmlElement(name = "ServicedOrganisations")
    protected ServicedOrganisationsStructure servicedOrganisations;
    @XmlElement(name = "NptgLocalities")
    protected TransXChangeNptgLocalitiesStructure nptgLocalities;
    @XmlElement(name = "StopPoints")
    protected TransXChangeStopPointsStructure stopPoints;
    @XmlElement(name = "StopAreas")
    protected StopAreasStructure stopAreas;
    @XmlElement(name = "RouteSections")
    protected RouteSectionsStructure routeSections;
    @XmlElement(name = "Routes")
    protected RoutesStructure routes;
    @XmlElement(name = "JourneyPatternSections")
    protected JourneyPatternSectionsStructure journeyPatternSections;
    @XmlElement(name = "Operators")
    protected OperatorsStructure operators;
    @XmlElement(name = "Services")
    protected ServicesStructure services;
    @XmlElement(name = "VehicleJourneys")
    protected VehicleJourneysStructure vehicleJourneys;
    @XmlElement(name = "Registrations")
    protected RegistrationsStructure registrations;
    @XmlElement(name = "SupportingDocuments")
    protected SupportingDocumentsStructure supportingDocuments;
    @XmlAttribute(name = "LocationSystem")
    protected LocationSystemEnumeration locationSystem;
    @XmlAttribute(name = "RegistrationDocument")
    protected RegistrationDocumentType registrationDocument;
    @XmlAttribute(name = "SchemaVersion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String schemaVersion;
    @XmlAttribute(name = "MappingSystem")
    protected MappingSystemEnumeration mappingSystem;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "CreationDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "ModificationDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modificationDateTime;
    @XmlAttribute(name = "Modification", required = true)
    protected ModificationEnumeration modification;
    @XmlAttribute(name = "RevisionNumber", required = true)
    protected BigInteger revisionNumber;
    @XmlAttribute(name = "FileName", required = true)
    protected String fileName;

    /**
     * Gets the value of the servicedOrganisations property.
     * 
     * @return
     *     possible object is
     *     {@link ServicedOrganisationsStructure }
     *     
     */
    public ServicedOrganisationsStructure getServicedOrganisations() {
        return servicedOrganisations;
    }

    /**
     * Sets the value of the servicedOrganisations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicedOrganisationsStructure }
     *     
     */
    public void setServicedOrganisations(ServicedOrganisationsStructure value) {
        this.servicedOrganisations = value;
    }

    /**
     * Gets the value of the nptgLocalities property.
     * 
     * @return
     *     possible object is
     *     {@link TransXChangeNptgLocalitiesStructure }
     *     
     */
    public TransXChangeNptgLocalitiesStructure getNptgLocalities() {
        return nptgLocalities;
    }

    /**
     * Sets the value of the nptgLocalities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransXChangeNptgLocalitiesStructure }
     *     
     */
    public void setNptgLocalities(TransXChangeNptgLocalitiesStructure value) {
        this.nptgLocalities = value;
    }

    /**
     * Gets the value of the stopPoints property.
     * 
     * @return
     *     possible object is
     *     {@link TransXChangeStopPointsStructure }
     *     
     */
    public TransXChangeStopPointsStructure getStopPoints() {
        return stopPoints;
    }

    /**
     * Sets the value of the stopPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransXChangeStopPointsStructure }
     *     
     */
    public void setStopPoints(TransXChangeStopPointsStructure value) {
        this.stopPoints = value;
    }

    /**
     * Gets the value of the stopAreas property.
     * 
     * @return
     *     possible object is
     *     {@link StopAreasStructure }
     *     
     */
    public StopAreasStructure getStopAreas() {
        return stopAreas;
    }

    /**
     * Sets the value of the stopAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopAreasStructure }
     *     
     */
    public void setStopAreas(StopAreasStructure value) {
        this.stopAreas = value;
    }

    /**
     * Gets the value of the routeSections property.
     * 
     * @return
     *     possible object is
     *     {@link RouteSectionsStructure }
     *     
     */
    public RouteSectionsStructure getRouteSections() {
        return routeSections;
    }

    /**
     * Sets the value of the routeSections property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteSectionsStructure }
     *     
     */
    public void setRouteSections(RouteSectionsStructure value) {
        this.routeSections = value;
    }

    /**
     * Gets the value of the routes property.
     * 
     * @return
     *     possible object is
     *     {@link RoutesStructure }
     *     
     */
    public RoutesStructure getRoutes() {
        return routes;
    }

    /**
     * Sets the value of the routes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutesStructure }
     *     
     */
    public void setRoutes(RoutesStructure value) {
        this.routes = value;
    }

    /**
     * Gets the value of the journeyPatternSections property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyPatternSectionsStructure }
     *     
     */
    public JourneyPatternSectionsStructure getJourneyPatternSections() {
        return journeyPatternSections;
    }

    /**
     * Sets the value of the journeyPatternSections property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyPatternSectionsStructure }
     *     
     */
    public void setJourneyPatternSections(JourneyPatternSectionsStructure value) {
        this.journeyPatternSections = value;
    }

    /**
     * Gets the value of the operators property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorsStructure }
     *     
     */
    public OperatorsStructure getOperators() {
        return operators;
    }

    /**
     * Sets the value of the operators property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorsStructure }
     *     
     */
    public void setOperators(OperatorsStructure value) {
        this.operators = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesStructure }
     *     
     */
    public ServicesStructure getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesStructure }
     *     
     */
    public void setServices(ServicesStructure value) {
        this.services = value;
    }

    /**
     * Gets the value of the vehicleJourneys property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleJourneysStructure }
     *     
     */
    public VehicleJourneysStructure getVehicleJourneys() {
        return vehicleJourneys;
    }

    /**
     * Sets the value of the vehicleJourneys property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleJourneysStructure }
     *     
     */
    public void setVehicleJourneys(VehicleJourneysStructure value) {
        this.vehicleJourneys = value;
    }

    /**
     * Gets the value of the registrations property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationsStructure }
     *     
     */
    public RegistrationsStructure getRegistrations() {
        return registrations;
    }

    /**
     * Sets the value of the registrations property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationsStructure }
     *     
     */
    public void setRegistrations(RegistrationsStructure value) {
        this.registrations = value;
    }

    /**
     * Gets the value of the supportingDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link SupportingDocumentsStructure }
     *     
     */
    public SupportingDocumentsStructure getSupportingDocuments() {
        return supportingDocuments;
    }

    /**
     * Sets the value of the supportingDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportingDocumentsStructure }
     *     
     */
    public void setSupportingDocuments(SupportingDocumentsStructure value) {
        this.supportingDocuments = value;
    }

    /**
     * Gets the value of the locationSystem property.
     * 
     * @return
     *     possible object is
     *     {@link LocationSystemEnumeration }
     *     
     */
    public LocationSystemEnumeration getLocationSystem() {
        return locationSystem;
    }

    /**
     * Sets the value of the locationSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationSystemEnumeration }
     *     
     */
    public void setLocationSystem(LocationSystemEnumeration value) {
        this.locationSystem = value;
    }

    /**
     * Gets the value of the registrationDocument property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationDocumentType }
     *     
     */
    public RegistrationDocumentType getRegistrationDocument() {
        if (registrationDocument == null) {
            return RegistrationDocumentType.FALSE;
        } else {
            return registrationDocument;
        }
    }

    /**
     * Sets the value of the registrationDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationDocumentType }
     *     
     */
    public void setRegistrationDocument(RegistrationDocumentType value) {
        this.registrationDocument = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "2.1";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the mappingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link MappingSystemEnumeration }
     *     
     */
    public MappingSystemEnumeration getMappingSystem() {
        return mappingSystem;
    }

    /**
     * Sets the value of the mappingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingSystemEnumeration }
     *     
     */
    public void setMappingSystem(MappingSystemEnumeration value) {
        this.mappingSystem = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the modificationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModificationDateTime() {
        return modificationDateTime;
    }

    /**
     * Sets the value of the modificationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModificationDateTime(XMLGregorianCalendar value) {
        this.modificationDateTime = value;
    }

    /**
     * Gets the value of the modification property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationEnumeration }
     *     
     */
    public ModificationEnumeration getModification() {
        return modification;
    }

    /**
     * Sets the value of the modification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationEnumeration }
     *     
     */
    public void setModification(ModificationEnumeration value) {
        this.modification = value;
    }

    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevisionNumber(BigInteger value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

}
