//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//


package uk.org.transxchange;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of one or more vehicle journeys.
 * 
 * <p>Java class for VehicleJourneysStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleJourneysStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="VehicleJourney" type="{http://www.transxchange.org.uk/}VehicleJourneyStructure" minOccurs="0"/>
 *         &lt;element name="FlexibleVehicleJourney" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.transxchange.org.uk/}FlexibleVehicleJourneyStructure">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleJourneysStructure", propOrder = {
    "vehicleJourneyAndFlexibleVehicleJourney"
})
public class VehicleJourneysStructure {

    @XmlElements({
        @XmlElement(name = "VehicleJourney", type = VehicleJourneyStructure.class),
        @XmlElement(name = "FlexibleVehicleJourney", type = VehicleJourneysStructure.FlexibleVehicleJourney.class)
    })
    protected List<AbstractVehicleJourneyStructure> vehicleJourneyAndFlexibleVehicleJourney;

    /**
     * Gets the value of the vehicleJourneyAndFlexibleVehicleJourney property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicleJourneyAndFlexibleVehicleJourney property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicleJourneyAndFlexibleVehicleJourney().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleJourneyStructure }
     * {@link VehicleJourneysStructure.FlexibleVehicleJourney }
     * 
     * 
     */
    public List<AbstractVehicleJourneyStructure> getVehicleJourneyAndFlexibleVehicleJourney() {
        if (vehicleJourneyAndFlexibleVehicleJourney == null) {
            vehicleJourneyAndFlexibleVehicleJourney = new ArrayList<AbstractVehicleJourneyStructure>();
        }
        return this.vehicleJourneyAndFlexibleVehicleJourney;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.transxchange.org.uk/}FlexibleVehicleJourneyStructure">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FlexibleVehicleJourney
        extends FlexibleVehicleJourneyStructure
    {


    }

}
