//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:57:01 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.govtalk.gov.uk/people/bs7666", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.gov.govtalk.people.bs7666;
